Predicting Madrid Housing Prices Using Socioeconomic prices using Machiene Learning

1. Import Libraries

In [1]:
# Import the Pandas library for data manipulation and analysis
import pandas as pd

# Import NumPy for numerical operations
import numpy as np

# Import Matplotlib for creating basic charts and graphs
import matplotlib.pyplot as plt

# Import Seaborn for creating attractive statistical visualisations
import seaborn as sns

2. Load Datasets

In [2]:
# Loading Dataset 2: Average Declared Housing Price (euros/m2) by District and Neighborhood in Madrid
prices = pd.read_csv("../data/prices.csv", sep=";",skiprows=5)

In [3]:
# Display the first five rows
prices.head()

,Unnamed: 0,Unnamed: 1,2007,2007.1,2007.2,2007.3,2007.4,2007.5,2007.6,2007.7,...,2024.8,2025,2025.1,2025.2,2025.3,2025.4,2025.5,2025.6,2025.7,2025.8
0,NaN,NaN,Euros/m2,Euros/m2,Euros/m2,Números índice (Madrid=100),Números índice (Madrid=100),Números índice (Madrid=100),Números índice (Total=100),Números índice (Total=100),...,Números índice (Total=100),Euros/m2,Euros/m2,Euros/m2,Números índice (Madrid=100),Números índice (Madrid=100),Números índice (Madrid=100),Números índice (Total=100),Números índice (Total=100),Números índice (Total=100)
1,NaN,NaN,Total,Nuevas,Usadas,Total,Nuevas,Usadas,Total,Nuevas,...,Usadas,Total,Nuevas,Usadas,Total,Nuevas,Usadas,Total,Nuevas,Usadas
2,Ciudad de Madrid,Ciudad de Madrid,"3.746,27","3.479,98","3.859,89",100,100,100,100,"92,89",...,"100,39","5.285,72","5.041,46","5.333,59",100,100,100,100,"95,38","100,91"
3,01. Centro,01. Centro,"4.798,92","4.988,4","4.768,62","128,1","143,35","123,54",100,"103,95",...,"100,18","7.147,7","6.814,13","7.171,36","135,23","135,16","134,46",100,"95,33","100,33"
4,01. Centro,011. Palacio,..,..,..,..,..,..,..,..,...,"99,32","6.895,15","6.421,28","6.954,58","130,45","127,37","130,39",100,"93,13","100,86"

In [4]:
# Display the first ten rows
prices.head(10)

,Unnamed: 0,Unnamed: 1,2007,2007.1,2007.2,2007.3,2007.4,2007.5,2007.6,2007.7,...,2024.8,2025,2025.1,2025.2,2025.3,2025.4,2025.5,2025.6,2025.7,2025.8
0,NaN,NaN,Euros/m2,Euros/m2,Euros/m2,Números índice (Madrid=100),Números índice (Madrid=100),Números índice (Madrid=100),Números índice (Total=100),Números índice (Total=100),...,Números índice (Total=100),Euros/m2,Euros/m2,Euros/m2,Números índice (Madrid=100),Números índice (Madrid=100),Números índice (Madrid=100),Números índice (Total=100),Números índice (Total=100),Números índice (Total=100)
1,NaN,NaN,Total,Nuevas,Usadas,Total,Nuevas,Usadas,Total,Nuevas,...,Usadas,Total,Nuevas,Usadas,Total,Nuevas,Usadas,Total,Nuevas,Usadas
2,Ciudad de Madrid,Ciudad de Madrid,"3.746,27","3.479,98","3.859,89",100,100,100,100,"92,89",...,"100,39","5.285,72","5.041,46","5.333,59",100,100,100,100,"95,38","100,91"
3,01. Centro,01. Centro,"4.798,92","4.988,4","4.768,62","128,1","143,35","123,54",100,"103,95",...,"100,18","7.147,7","6.814,13","7.171,36","135,23","135,16","134,46",100,"95,33","100,33"
4,01. Centro,011. Palacio,..,..,..,..,..,..,..,..,...,"99,32","6.895,15","6.421,28","6.954,58","130,45","127,37","130,39",100,"93,13","100,86"
5,01. Centro,012. Embajadores,..,..,..,..,..,..,..,..,...,"99,95","6.054,75","6.153,41","6.044,57","114,55","122,06","113,33",100,"101,63","99,83"
6,01. Centro,013. Cortes,..,..,..,..,..,..,..,..,...,"99,71","7.246,75",0,"7.246,75","137,1",0,"135,87",100,0,100
7,01. Centro,014. Justicia,..,..,..,..,..,..,..,..,...,100,"9.541,9","9.505,61","9.544,48","180,52","188,55","178,95",100,"99,62","100,03"
8,01. Centro,015. Universidad,..,..,..,..,..,..,..,..,...,"99,6","7.135,43","6.682,45","7.149,96","134,99","132,55","134,06",100,"93,65","100,2"
9,01. Centro,016. Sol,..,..,..,..,..,..,..,..,...,"101,95","7.696,61",0,"7.726,49","145,61",0,"144,86",100,0,"100,39"

In [5]:
# Display the last five rows
prices.tail()

,Unnamed: 0,Unnamed: 1,2007,2007.1,2007.2,2007.3,2007.4,2007.5,2007.6,2007.7,...,2024.8,2025,2025.1,2025.2,2025.3,2025.4,2025.5,2025.6,2025.7,2025.8
154,21. Barajas,215. Corralejos,..,..,..,..,..,..,..,..,...,"102,26","4.890,3",0,"4.902,36","92,52",0,"91,91",100,0,"100,25"
155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,Fuente: Colegio de Registradores de España,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,Observaciones: Tasa de cobertura: La informaci...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Display ten random rows
prices.sample(10)

,Unnamed: 0,Unnamed: 1,2007,2007.1,2007.2,2007.3,2007.4,2007.5,2007.6,2007.7,...,2024.8,2025,2025.1,2025.2,2025.3,2025.4,2025.5,2025.6,2025.7,2025.8
139,19. Vicálvaro,194. El Cañaveral,-,-,-,-,-,-,-,-,...,"107,03","4.587,55","4.652,24","4.116,01","86,79","92,28","77,17",100,"101,41","89,72"
20,03. Retiro,032. Adelfas,..,..,..,..,..,..,..,..,...,"98,87","5.741,86",0,"5.741,25","108,63",0,"107,64",100,0,"99,99"
153,21. Barajas,214. Timón,..,..,..,..,..,..,..,..,...,"100,23","4.418,93",0,"4.309,06","83,6",0,"80,79",100,0,"97,51"
19,03. Retiro,031. Pacífico,..,..,..,..,..,..,..,..,...,"99,58","6.286,22",0,"6.287,24","118,93",0,"117,88",100,0,"100,02"
107,14. Moratalaz,146. Vinateros,..,..,..,..,..,..,..,..,...,"100,49","3.899,66",0,"3.903,82","73,78",0,"73,19",100,0,"100,11"
149,21. Barajas,21. Barajas,"3.587,62","3.593,01","3.585,8","95,77","103,25","92,9",100,"100,15",...,"100,72","4.611,65","5.557,96","4.413,92","87,25","110,25","82,76",100,"120,52","95,71"
73,10. Latina,103. Lucero,..,..,..,..,..,..,..,..,...,"98,85","3.310,43","3.719,24","3.258,35","62,63","73,77","61,09",100,"112,35","98,43"
128,17. Villaverde,173. Butarque,..,..,..,..,..,..,..,..,...,"101,33","3.143,01","2.580,54","3.236,76","59,46","51,19","60,69",100,"82,1","102,98"
74,10. Latina,104. Aluche,..,..,..,..,..,..,..,..,...,"100,28","3.360,3","3.209,44","3.376,52","63,57","63,66","63,31",100,"95,51","100,48"
47,07. Chamberí,071. Gaztambide,..,..,..,..,..,..,..,..,...,"96,34","7.413,6","7.431,02","7.412,01","140,26","147,4","138,97",100,"100,23","99,98"

In [7]:
# Check the number of rows and columns
prices.shape

(159, 173)

In [8]:
# Display all column names
prices.columns

Index(['Unnamed: 0', 'Unnamed: 1', '2007', '2007.1', '2007.2', '2007.3',
       '2007.4', '2007.5', '2007.6', '2007.7',
       ...
       '2024.8', '2025', '2025.1', '2025.2', '2025.3', '2025.4', '2025.5',
       '2025.6', '2025.7', '2025.8'],
      dtype='object', length=173)

In [9]:
# Display the data type of each column
prices.dtypes

Unnamed: 0    object
Unnamed: 1    object
2007          object
2007.1        object
2007.2        object
               ...
2025.4        object
2025.5        object
2025.6        object
2025.7        object
2025.8        object
Length: 173, dtype: object

In [10]:
# Display dataset information
prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Columns: 173 entries, Unnamed: 0 to 2025.8
dtypes: object(173)
memory usage: 215.0+ KB

In [11]:
# Summary statistics
prices.describe()

,Unnamed: 0,Unnamed: 1,2007,2007.1,2007.2,2007.3,2007.4,2007.5,2007.6,2007.7,...,2024.8,2025,2025.1,2025.2,2025.3,2025.4,2025.5,2025.6,2025.7,2025.8
count,155,153,155,155,155,155,155,155,155,155,...,155,155,155,155,155,155,155,155,155,155
unique,24,153,26,26,26,26,26,26,5,26,...,133,155,94,154,155,94,154,3,94,125
top,15. Ciudad Lineal,Ciudad de Madrid,..,..,..,..,..,..,..,..,...,100,Euros/m2,0,0,Números índice (Madrid=100),0,0,100,0,100
freq,10,1,128,128,128,128,128,128,128,128,...,10,1,62,2,1,62,2,153,62,8

In [12]:
# Summary statistics for all columns
prices.describe(include="all")

,Unnamed: 0,Unnamed: 1,2007,2007.1,2007.2,2007.3,2007.4,2007.5,2007.6,2007.7,...,2024.8,2025,2025.1,2025.2,2025.3,2025.4,2025.5,2025.6,2025.7,2025.8
count,155,153,155,155,155,155,155,155,155,155,...,155,155,155,155,155,155,155,155,155,155
unique,24,153,26,26,26,26,26,26,5,26,...,133,155,94,154,155,94,154,3,94,125
top,15. Ciudad Lineal,Ciudad de Madrid,..,..,..,..,..,..,..,..,...,100,Euros/m2,0,0,Números índice (Madrid=100),0,0,100,0,100
freq,10,1,128,128,128,128,128,128,128,128,...,10,1,62,2,1,62,2,153,62,8

In [13]:
# Count missing values
prices.isnull().sum()

Unnamed: 0    4
Unnamed: 1    6
2007          4
2007.1        4
2007.2        4
             ..
2025.4        4
2025.5        4
2025.6        4
2025.7        4
2025.8        4
Length: 173, dtype: int64

In [14]:
# Count duplicate rows
prices.duplicated().sum()

np.int64(1)

In [15]:
# Count unique values
# A method that counts the number of unique (distinct) values in each column.
prices.nunique()

Unnamed: 0     24
Unnamed: 1    153
2007           26
2007.1         26
2007.2         26
             ...
2025.4         94
2025.5        154
2025.6          3
2025.7         94
2025.8        125
Length: 173, dtype: int64