Predicting Madrid Housing Prices Using Socioeconomic Indicators using Machine Learning

1. Import Libraries

In [4]:
# Import the Pandas library for data manipulation and analysis
import pandas as pd

# Import NumPy for numerical operations
import numpy as np

# Import Matplotlib for creating basic charts and graphs
import matplotlib.pyplot as plt

# Import Seaborn for creating attractive statistical visualisations
import seaborn as sns

2. Load Datasets

In [5]:
# Loading Dataset 1: Panel of Sociodemographic Indicators of Districts and Neighborhoods of Madrid
indicators = pd.read_csv("../data/indicators.csv",sep=";")

In [6]:
# Display the first five rows
indicators.head()

,Orden,Periodo panel,ciudad,cod_distrito,distrito,cod_barrio,barrio,año,fecha_indicador,fuente_indicador,categoría_1,categoría_2,indicador_nivel1,indicador_nivel2,indicador_nivel3,unidad_indicador,indicador_completo,valor_indicador
0,1,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),523
1,2,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),258
2,3,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,134881
3,4,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,67829
4,5,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,67052

In [7]:
# Display the first ten rows
indicators.head(10)

,Orden,Periodo panel,ciudad,cod_distrito,distrito,cod_barrio,barrio,año,fecha_indicador,fuente_indicador,categoría_1,categoría_2,indicador_nivel1,indicador_nivel2,indicador_nivel3,unidad_indicador,indicador_completo,valor_indicador
0,1,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),523
1,2,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),258
2,3,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,134881
3,4,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,67829
4,5,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,67052
5,6,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Edad Media,NaN,NaN,Edad,Edad media de la población,"44,03"
6,7,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,0-14,NaN,Personas,Población de 0 a 14 años,10554
7,8,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,15-29,NaN,Personas,Población de 15 a 29 años,21800
8,9,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,30-44,NaN,Personas,Población de 30 a 44 años,42857
9,10,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,45-64,NaN,Personas,Población de 45 a 64 años,38025

In [8]:
# Display the last five rows
indicators.tail()

,Orden,Periodo panel,ciudad,cod_distrito,distrito,cod_barrio,barrio,año,fecha_indicador,fuente_indicador,categoría_1,categoría_2,indicador_nivel1,indicador_nivel2,indicador_nivel3,unidad_indicador,indicador_completo,valor_indicador
116903,116904,2025,Ciudad de Madrid,18.0,Villa de Vallecas,NaN,NaN,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Salud,Discapacidad reconocida,Número de mujeres,Feminización Discapacidad,Mujeres,Porcentaje,Mujeres por cada 100 hombres (feminización de ...,"106,3"
116904,116905,2025,Ciudad de Madrid,19.0,Vicálvaro,NaN,NaN,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Salud,Discapacidad reconocida,Número de mujeres,Feminización Discapacidad,Mujeres,Porcentaje,Mujeres por cada 100 hombres (feminización de ...,"101,31"
116905,116906,2025,Ciudad de Madrid,20.0,San Blas-Canillejas,NaN,NaN,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Salud,Discapacidad reconocida,Número de mujeres,Feminización Discapacidad,Mujeres,Porcentaje,Mujeres por cada 100 hombres (feminización de ...,"97,54"
116906,116907,2025,Ciudad de Madrid,21.0,Barajas,NaN,NaN,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Salud,Discapacidad reconocida,Número de mujeres,Feminización Discapacidad,Mujeres,Porcentaje,Mujeres por cada 100 hombres (feminización de ...,"100,64"
116907,116908,2025,Ciudad de Madrid,NaN,NaN,NaN,NaN,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Salud,Discapacidad reconocida,Número de mujeres,Feminización Discapacidad,Mujeres,Porcentaje,Mujeres por cada 100 hombres (feminización de ...,"110,04"

In [9]:
# Display ten random rows
indicators.sample(10)

,Orden,Periodo panel,ciudad,cod_distrito,distrito,cod_barrio,barrio,año,fecha_indicador,fuente_indicador,categoría_1,categoría_2,indicador_nivel1,indicador_nivel2,indicador_nivel3,unidad_indicador,indicador_completo,valor_indicador
106232,106233,2025,Ciudad de Madrid,11.0,Carabanchel,115.0,Puerta Bonita,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,15-29,NaN,Personas,Población de 15 a 29 años,8121
92559,92560,2024,Ciudad de Madrid,21.0,Barajas,NaN,NaN,2023,01/01/2023,Estadística Ayuntamiento de Madrid,Educación,Población en etapas educativas,Número de personas,de 12 a 15 años,Niños,Personas,Población infantil masculina en etapa educativ...,1223
78030,78031,2024,Ciudad de Madrid,2.0,Arganzuela,25.0,Delicias,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Indicadores Población desempleo,Población desempleo,Número de personas paradas,Hombres,Población de 16 a 24 años,Tasa,Tasa de desempleo en hombres de 16 a 24 años,"2,08"
110748,110749,2025,Ciudad de Madrid,16.0,Hortaleza,NaN,NaN,2024,01/01/2024,Portal de datos abiertos del Ayuntamiento de M...,Servicios y equipamientos Municipales,Servicios Sociales Municipales,Número de equipamientos,Apartamentos Municipales para Mayores,NaN,Equipamientos,Apartamentos municipales para mayores,0
59781,59782,2023,Ciudad de Madrid,4.0,Salamanca,NaN,NaN,2022,01/01/2022,Portal de datos abiertos del Ayuntamiento de M...,Seguridad,Intervención de la Policía Municipal,Número de intervenciones,Seguridad,Población delitos relacionados con personas,Intervenciones,Intervenciones de la policía municipal en mate...,100
88874,88875,2024,Ciudad de Madrid,15.0,Ciudad Lineal,159.0,Costillares,2023,01/01/2023,Portal web del Ayuntamiento de Madrid (https:/...,Índice de vulnerabilidad,Territorial,Resultado del índice,Vulnerabilidad,Medio Ambiente Urbano y Movilidad,Índice,Índice de vulnerabilidad medio ambiente urbano...,"7,152891623"
22014,22015,2021,Ciudad de Madrid,5.0,Chamartín,NaN,NaN,2020,01/01/2020,Portal de datos abiertos del Ayuntamiento de M...,Servicios y equipamientos Municipales,Servicios Sociales Municipales,Número de equipamientos,Centros de Servicios Sociales,NaN,Equipamientos,Centros de servicios sociales,1
77935,77936,2024,Ciudad de Madrid,2.0,Arganzuela,24.0,Legazpi,2023,01/01/2023,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Edad Media,NaN,NaN,Edad,Edad media de la población,"40,5"
13898,13899,2020,Ciudad de Madrid,17.0,Villaverde,172.0,San Cristóbal,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,16052
79807,79808,2024,Ciudad de Madrid,4.0,Salamanca,NaN,NaN,2023,01/01/2023,Estadística Ayuntamiento de Madrid,Servicios Sociales,Personas mayores,Número de personas,Servicio de Ayuda a Domicilio,Mujeres,Personas,Personas con servicio de ayuda a domicilio (mo...,1347

In [10]:
# Check the number of rows and columns
indicators.shape

(116908, 18)

In [11]:
# Display all column names
indicators.columns

Index(['Orden', 'Periodo panel', 'ciudad', 'cod_distrito', 'distrito',
       'cod_barrio', 'barrio', 'año', 'fecha_indicador', 'fuente_indicador',
       'categoría_1', 'categoría_2', 'indicador_nivel1', 'indicador_nivel2',
       'indicador_nivel3', 'unidad_indicador', 'indicador_completo',
       'valor_indicador'],
      dtype='object')

Output of column names (English):

Index(['Order', 'Panel period', 'City', 'District code', 'District',
       'Neighborhood code', 'Neighborhood', 'Year', 'Indicator date', 'Indicator source',
       'Category 1', 'Category 2', 'Indicator level 1', 'Indicator level 2',
       'Indicator level 3', 'Indicator unit', 'Full indicator name',
       'Indicator value'],
      dtype='object')

In [12]:
# Display the data type of each column
indicators.dtypes

Orden                   int64
Periodo panel           int64
ciudad                 object
cod_distrito          float64
distrito               object
cod_barrio            float64
barrio                 object
año                     int64
fecha_indicador        object
fuente_indicador       object
categoría_1            object
categoría_2            object
indicador_nivel1       object
indicador_nivel2       object
indicador_nivel3       object
unidad_indicador       object
indicador_completo     object
valor_indicador        object
dtype: object

In [13]:
# Display dataset information
indicators.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116908 entries, 0 to 116907
Data columns (total 18 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Orden               116908 non-null  int64
 1   Periodo panel       116908 non-null  int64
 2   ciudad              116908 non-null  object
 3   cod_distrito        115105 non-null  float64
 4   distrito            115105 non-null  object
 5   cod_barrio          84570 non-null   float64
 6   barrio              84570 non-null   object
 7   año                 116908 non-null  int64
 8   fecha_indicador     116908 non-null  object
 9   fuente_indicador    116908 non-null  object
 10  categoría_1         116908 non-null  object
 11  categoría_2         100705 non-null  object
 12  indicador_nivel1    116908 non-null  object
 13  indicador_nivel2    103504 non-null  object
 14  indicador_nivel3    48898 non-null   object
 15  unidad_indicador    116908 non-null  object
 16  indicador_completo  116908 non-null  object
 17  valor_indicador     116908 non-null  object
dtypes: float64(2), int64(3), object(13)
memory usage: 16.1+ MB

In [14]:
# Summary statistics
indicators.describe()

,Orden,Periodo panel,cod_distrito,cod_barrio,año
count,116908.000000,116908.000000,115105.000000,84570.000000,116908.000000
mean,58454.500000,2022.539561,10.777282,110.687194,2021.616776
std,33748.576972,1.713728,5.911289,58.583824,1.946883
min,1.000000,2020.000000,1.000000,11.000000,2008.000000
25%,29227.750000,2021.000000,6.000000,62.000000,2020.000000
50%,58454.500000,2023.000000,11.000000,111.000000,2022.000000
75%,87681.250000,2024.000000,15.000000,158.000000,2023.000000
max,116908.000000,2025.000000,21.000000,215.000000,2025.000000

In [15]:
# Summary statistics for all columns
indicators.describe(include="all")

,Orden,Periodo panel,ciudad,cod_distrito,distrito,cod_barrio,barrio,año,fecha_indicador,fuente_indicador,categoría_1,categoría_2,indicador_nivel1,indicador_nivel2,indicador_nivel3,unidad_indicador,indicador_completo,valor_indicador
count,116908.000000,116908.000000,116908,115105.000000,115105,84570.000000,84570,116908.000000,116908,116908,116908,100705,116908,103504,48898,116908,116908,116908
unique,NaN,NaN,1,NaN,21,NaN,131,NaN,31,12,19,53,46,226,65,41,381,28852
top,NaN,NaN,Ciudad de Madrid,NaN,Ciudad Lineal,NaN,Villaverde Alto - Casco Histórico de Villaverde,NaN,01/01/2023,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de personas,Mujeres,Municipio,Personas,Superficie (ha.),1
freq,NaN,NaN,116908,NaN,7183,NaN,707,NaN,17246,89172,31665,23170,29881,9010,8711,44180,918,5245
mean,58454.500000,2022.539561,NaN,10.777282,NaN,110.687194,NaN,2021.616776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,33748.576972,1.713728,NaN,5.911289,NaN,58.583824,NaN,1.946883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,2020.000000,NaN,1.000000,NaN,11.000000,NaN,2008.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,29227.750000,2021.000000,NaN,6.000000,NaN,62.000000,NaN,2020.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,58454.500000,2023.000000,NaN,11.000000,NaN,111.000000,NaN,2022.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,87681.250000,2024.000000,NaN,15.000000,NaN,158.000000,NaN,2023.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,116908.000000,2025.000000,NaN,21.000000,NaN,215.000000,NaN,2025.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Count missing values
indicators.isnull().sum()

Orden                     0
Periodo panel             0
ciudad                    0
cod_distrito           1803
distrito               1803
cod_barrio            32338
barrio                32338
año                       0
fecha_indicador           0
fuente_indicador          0
categoría_1               0
categoría_2           16203
indicador_nivel1          0
indicador_nivel2      13404
indicador_nivel3      68010
unidad_indicador          0
indicador_completo        0
valor_indicador           0
dtype: int64

In [17]:
# Count duplicate rows
indicators.duplicated().sum()

np.int64(0)

In [18]:
# Count unique values
# A method that counts the number of unique (distinct) values in each column.
indicators.nunique()

Orden                 116908
Periodo panel              6
ciudad                     1
cod_distrito              21
distrito                  21
cod_barrio               131
barrio                   131
año                       18
fecha_indicador           31
fuente_indicador          12
categoría_1               19
categoría_2               53
indicador_nivel1          46
indicador_nivel2         226
indicador_nivel3          65
unidad_indicador          41
indicador_completo       381
valor_indicador        28852
dtype: int64