Predicting Madrid Housing Prices Using Socioeconomic Indicators using Machine Learning

In [20]:
# Import the Pandas library for data manipulation and analysis
import pandas as pd

# Import NumPy for numerical operations
import numpy as np

# Import Matplotlib for creating basic charts and graphs
import matplotlib.pyplot as plt

# Import Seaborn for creating attractive statistical visualisations
import seaborn as sns

In [21]:
# Loading Dataset 1: Panel of Sociodemographic Indicators of Districts and Neighborhoods of Madrid
indicators = pd.read_csv("../data/indicators.csv",sep=";")

In [24]:
# Create a clean working copy of dataset
indicators_clean = indicators.copy()

In [25]:
# Display the first five rows
indicators_clean.head()

,Orden,Periodo panel,ciudad,cod_distrito,distrito,cod_barrio,barrio,año,fecha_indicador,fuente_indicador,categoría_1,categoría_2,indicador_nivel1,indicador_nivel2,indicador_nivel3,unidad_indicador,indicador_completo,valor_indicador
0,1,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),523
1,2,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),258
2,3,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,134881
3,4,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,67829
4,5,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,67052

In [26]:
# Rename columns

indicators_clean.rename(columns={
    "Orden": "row_no",
    "Periodo panel": "dataset_version",
    "ciudad": "city",
    "cod_distrito": "district_code",
    "distrito": "district_name",
    "cod_barrio": "neighbourhood_code",
    "barrio": "neighbourhood_name",
    "año": "year",
    "fecha_indicador": "date",
    "fuente_indicador": "data_source",
    "categoría_1": "main_category",
    "categoría_2": "subcategory",
    "indicador_nivel1": "indicator_level1",
    "indicador_nivel2": "indicator_level2",
    "indicador_nivel3": "indicator_level3",
    "unidad_indicador": "unit",
    "indicador_completo": "indicator_name",
    "valor_indicador": "indicator_value"
}, inplace=True)

In [27]:
# Display the first ten rows following column rename
indicators_clean.head(10)

,row_no,dataset_version,city,district_code,district_name,neighbourhood_code,neighbourhood_name,year,date,data_source,main_category,subcategory,indicator_level1,indicator_level2,indicator_level3,unit,indicator_name,indicator_value
0,1,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),523
1,2,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),258
2,3,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,134881
3,4,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,67829
4,5,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,67052
5,6,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Edad Media,NaN,NaN,Edad,Edad media de la población,"44,03"
6,7,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,0-14,NaN,Personas,Población de 0 a 14 años,10554
7,8,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,15-29,NaN,Personas,Población de 15 a 29 años,21800
8,9,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,30-44,NaN,Personas,Población de 30 a 44 años,42857
9,10,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,45-64,NaN,Personas,Población de 45 a 64 años,38025

In [53]:
# Checking dataset coverage across different years
indicators_clean["dataset_version"].value_counts().sort_index()

dataset_version
2020    18846
2021    19493
2022    18906
2023    19578
2024    19569
2025    20516
Name: count, dtype: int64

In [64]:
#Display unique dataset names
indicators_clean["neighbourhood_name"].nunique()

131

In [66]:
# Remove rows where neighbourhood_name is missing

indicators_clean_n= indicators_clean.dropna(subset=["neighbourhood_name"])

In [68]:
indicators_clean_n.sample(10)

,row_no,dataset_version,city,district_code,district_name,neighbourhood_code,neighbourhood_name,year,date,data_source,main_category,subcategory,indicator_level1,indicator_level2,indicator_level3,unit,indicator_name,indicator_value
85293,85294,2024,Ciudad de Madrid,11.0,Carabanchel,115.0,Puerta Bonita,2024,01/02/2024,Estadística Ayuntamiento de Madrid,Indicadores Población desempleo,Población desempleo,Número de personas paradas,Mujeres,NaN,Personas,Paro registrado (número de personas registrada...,1243
51412,51413,2022,Ciudad de Madrid,17.0,Villaverde,173.0,Butarque,2021,01/01/2021,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,Nacionalidad española,Personas,Personas con nacionalidad española mujeres,9056
51170,51171,2022,Ciudad de Madrid,17.0,Villaverde,173.0,Butarque,2021,01/01/2021,Estadística Ayuntamiento de Madrid,Educación,Población en etapas educativas,Número de personas,NaN,Niños,Personas,Etapas educativas. total niños,2507
55951,55952,2022,Ciudad de Madrid,3.0,Retiro,35.0,Los Jerónimos,2021,01/01/2021,Estadística Ayuntamiento de Madrid,Indicadores Económicos,Indicadores económicos,Pensión,Hombres,NaN,Euros,Pensión media mensual hombres,1.845
20645,20646,2021,Ciudad de Madrid,3.0,Retiro,31.0,Pacífico,2020,01/01/2020,Portal de datos abiertos del Ayuntamiento de M...,Servicios y equipamientos Municipales,Deportes,Número de equipamientos,Piscinas cubiertas,NaN,Equipamientos,Piscinas cubiertas,1
8838,8839,2020,Ciudad de Madrid,11.0,Carabanchel,114.0,Vista Alegre,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Educación,Población en etapas educativas,Número de personas,de 0 a 2 años,Niños,Personas,Población infantil masculina en etapa educativ...,535
26441,26442,2021,Ciudad de Madrid,10.0,Latina,107.0,Águilas,2020,01/01/2020,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Rumanía,Primera y segunda nacionalidad del distrito,Personas,Primera y segunda nacionalidad extranjera en e...,906
68658,68659,2023,Ciudad de Madrid,14.0,Moratalaz,144.0,Media Legua,2021,01/01/2021,Estadística Ayuntamiento de Madrid,Población del distrito,Dinámica demográfica,Crecimiento Demográfico,NaN,NaN,Tasa,Tasa de crecimiento demográfico (porcentaje),"-1,62"
83076,83077,2024,Ciudad de Madrid,8.0,Fuencarral-El Pardo,88.0,El Goloso,2023,01/01/2023,Estadística Ayuntamiento de Madrid,Educación,Nivel de estudios de la población,Número de personas,"Estudios superiores, licenciatura, grado, arq...",NaN,Personas,Población mayor/igual de 25 años con estudios ...,6733
40793,40794,2022,Ciudad de Madrid,4.0,Salamanca,42.0,Goya,2022,01/02/2022,Estadística Ayuntamiento de Madrid,Indicadores Población desempleo,Indicadores Desempleo,Número de personas paradas,Hombres,NaN,Personas,Paro registrado (número de personas registrada...,295

In [83]:
indicators_clean_n[
    ["neighbourhood_code", "neighbourhood_name"]
].drop_duplicates().head(20)

      neighbourhood_code    neighbourhood_name
186                 11.0               Palacio
269                 12.0           Embajadores
351                 13.0                Cortes
425                 14.0              Justicia
508                 15.0           Universidad
591                 16.0                   Sol
995                 21.0              Imperial
1070                22.0               Acacias
1148                23.0               Chopera
1227                24.0               Legazpi
1301                25.0              Delicias
1376                26.0  Palos de la Frontera
1456                27.0                Atocha
1868                31.0              Pacífico
1949                32.0               Adelfas
2026                33.0              Estrella
2104                34.0                 Ibiza
2180                35.0         Los Jerónimos
2256                36.0            Niño Jesús
2652                41.0             Recoletos

In [54]:
#
#
#
#
Display information for 1 district 

centro_district = indicators_clean.loc[
    (indicators_clean['dataset_version'] == 2025) &
    (indicators_clean['district_name'] == 'Centro') &
    (indicators_clean['neighbourhood_code'].isna())
]

centro_district

# There are 256 rows so there is a lot of data, I want to keep the most relevant

,row_no,dataset_version,city,district_code,district_name,neighbourhood_code,neighbourhood_name,year,date,data_source,main_category,subcategory,indicator_level1,indicator_level2,indicator_level3,unit,indicator_name,indicator_value
96304,96305,2025,Ciudad de Madrid,1.0,Centro,NaN,NaN,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),"522,82"
96305,96306,2025,Ciudad de Madrid,1.0,Centro,NaN,NaN,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),"279,9223442"
96306,96307,2025,Ciudad de Madrid,1.0,Centro,NaN,NaN,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,146349
96307,96308,2025,Ciudad de Madrid,1.0,Centro,NaN,NaN,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,74247
96308,96309,2025,Ciudad de Madrid,1.0,Centro,NaN,NaN,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,72102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116798,116799,2025,Ciudad de Madrid,1.0,Centro,NaN,NaN,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Servicios y equipamientos Municipales,Deportes,Número de equipamientos,Campos de fútbol 11,NaN,Equipamientos,Campos de fútbol 11,0
116820,116821,2025,Ciudad de Madrid,1.0,Centro,NaN,NaN,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Salud,Discapacidad reconocida,Número de personas,Grado reconocido,NaN,Personas,Número de personas con grado de discapacidad r...,14621
116821,116822,2025,Ciudad de Madrid,1.0,Centro,NaN,NaN,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Salud,Discapacidad reconocida,Número de personas,Grado reconocido,Hombres,Personas,Número de personas con grado de discapacidad r...,7314
116822,116823,2025,Ciudad de Madrid,1.0,Centro,NaN,NaN,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Salud,Discapacidad reconocida,Número de personas,Grado reconocido,Mujeres,Personas,Número de personas con grado de discapacidad r...,7307
116886,116887,2025,Ciudad de Madrid,1.0,Centro,NaN,NaN,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Salud,Discapacidad reconocida,Número de mujeres,Feminización Discapacidad,Mujeres,Porcentaje,Mujeres por cada 100 hombres (feminización de ...,"99,9"

In [55]:
# Display the diffrerent main categories of the indicators

centro_district["main_category"].value_counts()

main_category
Población del distrito                           42
Salud                                            40
Educación                                        37
Servicios y equipamientos Municipales            34
Indicadores Población desempleo                  21
Calidad de vida                                  16
Servicios Sociales                               14
Resultados Elecciones Locales                    10
Seguridad                                         8
Índice de vulnerabilidad                          6
Vivienda                                          6
Empresa y comercio                                5
Participación ciudadana                           5
Indicadores Económicos                            4
Características Generales del Distrito-Barrio     2
Medio ambiente y residuos                         2
Name: count, dtype: int64

In [56]:
# Display the diffrerent subcateogries of the indicators

centro_district["subcategory"].value_counts()

subcategory
Estructura de población                                      30
Indicadores de Salud                                         27
Población desempleo                                          21
Población en etapas educativas                               15
Escolarización de alumnos por tipo de centro                 12
Servicios Sociales Municipales                               10
Hábitos y estilos de vida                                     9
Educación                                                     7
Nivel de estudios de la población                             7
Deportes                                                      7
Dinámica demográfica                                          6
Territorial                                                   6
Intervención de la Policía Municipal                          6
Satisfacción con espacios públicos                            6
Estructura de los hogares                                     6
Personas mayores                                              6
Población general                                             5
Entidades de participación ciudadana                          5
Zonas verdes                                                  4
Discapacidad reconocida                                       4
Indicadores económicos                                        4
Menores y familia                                             3
Percepción de la seguridad                                    3
Programa de prevención y control del absentismo escolar       3
Cultura                                                       3
Principales poblemas de la ciudadanía                         3
Calidad de vida y agenda pública                              2
Recogida domiciliaria de residuos sólidos                     2
Salud                                                         2
Ciudadanía                                                    1
Inspecciones y actuaciones                                    1
Género                                                        1
Población detenida e investigada por la Policía Municipal     1
Amigabilidad de la ciudad                                     1
Total locales                                                 1
Locales abiertos                                              1
Locales cerrados                                              1
Locales en uso como vivienda                                  1
Recursos municipales                                          1
Name: count, dtype: int64

In [59]:
# Retain only columns with information on types of indicies
centro_district[
    [
        "main_category",
        "subcategory",
        "indicator_name",
        "unit"
    ]]

,main_category,subcategory,indicator_name,unit
96304,Características Generales del Distrito-Barrio,NaN,Superficie (ha.),Ha
96305,Características Generales del Distrito-Barrio,NaN,Población densidad (hab./ha.),Habitantes/Ha.
96306,Población del distrito,Estructura de población,Número habitantes,Habitantes
96307,Población del distrito,Estructura de población,Población hombres,Habitantes
96308,Población del distrito,Estructura de población,Población mujeres,Habitantes
...,...,...,...,...
116798,Servicios y equipamientos Municipales,Deportes,Campos de fútbol 11,Equipamientos
116820,Salud,Discapacidad reconocida,Número de personas con grado de discapacidad r...,Personas
116821,Salud,Discapacidad reconocida,Número de personas con grado de discapacidad r...,Personas
116822,Salud,Discapacidad reconocida,Número de personas con grado de discapacidad r...,Personas
116886,Salud,Discapacidad reconocida,Mujeres por cada 100 hombres (feminización de ...,Porcentaje

In [60]:
# Remove duplicates
indicator_catalog = indicator_catalog.drop_duplicates()

In [61]:
# Sort alphabetically
indicator_catalog = indicator_catalog.sort_values(
    ["main_category", "subcategory", "indicator_name"]
)

In [63]:
# Save to Excel
indicator_catalog.to_excel(
    "../outputs/indicator_catalog.xlsx",
    index=False
)