# Predicting Madrid Housing Prices Using Socioeconomic Indicators using Machine Learning

In [392]:
# Import the Pandas library for data manipulation and analysis
import pandas as pd

# Import NumPy for numerical operations
import numpy as np

# Import Matplotlib for creating basic charts and graphs
import matplotlib.pyplot as plt

# Import Seaborn for creating attractive statistical visualisations
import seaborn as sns

In [393]:
# Loading Dataset 1: Panel of Sociodemographic Indicators of Districts and Neighborhoods of Madrid
indicators = pd.read_csv("../data/indicators.csv",sep=";")

In [394]:
# Create a clean working copy of dataset
indicators_2025 = indicators.copy()

In [395]:
# Display the first five rows
indicators_2025.head()

,Orden,Periodo panel,ciudad,cod_distrito,distrito,cod_barrio,barrio,año,fecha_indicador,fuente_indicador,categoría_1,categoría_2,indicador_nivel1,indicador_nivel2,indicador_nivel3,unidad_indicador,indicador_completo,valor_indicador
0,1,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),523
1,2,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),258
2,3,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,134881
3,4,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,67829
4,5,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,67052

In [396]:
# Rename columns

indicators_2025.rename(columns={
    "Orden": "row_no",
    "Periodo panel": "dataset_version",
    "ciudad": "city",
    "cod_distrito": "district_code",
    "distrito": "district_name",
    "cod_barrio": "neighbourhood_code",
    "barrio": "neighbourhood_name",
    "año": "year",
    "fecha_indicador": "date",
    "fuente_indicador": "data_source",
    "categoría_1": "main_category",
    "categoría_2": "subcategory",
    "indicador_nivel1": "indicator_level1",
    "indicador_nivel2": "indicator_level2",
    "indicador_nivel3": "indicator_level3",
    "unidad_indicador": "unit",
    "indicador_completo": "indicator_name",
    "valor_indicador": "indicator_value"
}, inplace=True)

In [397]:
# Display the first ten rows following column rename
indicators_2025.head(10)

,row_no,dataset_version,city,district_code,district_name,neighbourhood_code,neighbourhood_name,year,date,data_source,main_category,subcategory,indicator_level1,indicator_level2,indicator_level3,unit,indicator_name,indicator_value
0,1,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),523
1,2,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),258
2,3,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,134881
3,4,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,67829
4,5,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,67052
5,6,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Edad Media,NaN,NaN,Edad,Edad media de la población,"44,03"
6,7,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,0-14,NaN,Personas,Población de 0 a 14 años,10554
7,8,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,15-29,NaN,Personas,Población de 15 a 29 años,21800
8,9,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,30-44,NaN,Personas,Población de 30 a 44 años,42857
9,10,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,45-64,NaN,Personas,Población de 45 a 64 años,38025

In [398]:
# Check number of shapes and rows 
indicators_2025.shape

(116908, 18)

In [399]:
# Display unique dataset names
indicators_2025["neighbourhood_name"].nunique()

131

In [400]:
# Remove rows where neighbourhood_name is missing
indicators_2025= indicators_2025.dropna(subset=["neighbourhood_name"])

In [401]:
# Check number of shapes and rows 
indicators_2025.shape

(84570, 18)

In [402]:
# Check a sample 
indicators_2025.sample(10)

,row_no,dataset_version,city,district_code,district_name,neighbourhood_code,neighbourhood_name,year,date,data_source,main_category,subcategory,indicator_level1,indicator_level2,indicator_level3,unit,indicator_name,indicator_value
71509,71510,2023,Ciudad de Madrid,17.0,Villaverde,171.0,Villaverde Alto - Casco Histórico de Villaverde,2023,28/05/2023,Estadística Ayuntamiento de Madrid,Resultados Elecciones Locales,NaN,Número de votos,Partido Socialista Obrero Español,Municipio,Votos,"Elecciones municipales, votos al Partido Socia...",4732
59167,59168,2023,Ciudad de Madrid,3.0,Retiro,33.0,Estrella,2023,01/01/2023,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,10393
64895,64896,2023,Ciudad de Madrid,10.0,Latina,101.0,Los Cármenes,2022,01/01/2022,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Población mayor de 80 años/ Población mayor de...,NaN,Proporción,Porcentaje de sobre-envejecimiento (población ...,"35,07"
2397,2398,2020,Ciudad de Madrid,3.0,Retiro,33.0,Estrella,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,Nacionalidad extranjera,Personas,Personas con nacionalidad extranjera hombres,397
38599,38600,2022,Ciudad de Madrid,1.0,Centro,13.0,Cortes,2021,01/01/2021,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de los hogares,Número de Hogares,monoparentales: un hombre adulto con uno o más...,NaN,Hogares,Hogares monoparentales: un hombre adulto con u...,11
33999,34000,2021,Ciudad de Madrid,20.0,San Blas-Canillejas,208.0,El Salvador,2021,01/02/2021,Estadística Ayuntamiento de Madrid,Indicadores Población desempleo,Indicadores Desempleo,Número de personas paradas,Mujeres,NaN,Tasa,Tasa absoluta de paro registrado mujeres,"8,2"
369,370,2020,Ciudad de Madrid,1.0,Centro,13.0,Cortes,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Italia,Primera y segunda nacionalidad del distrito,Personas,Primera y segunda nacionalidad extranjera en e...,263
98694,98695,2025,Ciudad de Madrid,3.0,Retiro,34.0,Ibiza,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Índice de dependencia,NaN,Índice,Índice de dependencia (población de 0-15 + pob...,"0,5804"
97437,97438,2025,Ciudad de Madrid,2.0,Arganzuela,21.0,Imperial,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de los hogares,Número de Hogares,NaN,NaN,Hogares,Total hogares,10011
74156,74157,2023,Ciudad de Madrid,21.0,Barajas,214.0,Timón,2020,01/01/2020,Estadística Ayuntamiento de Madrid,Indicadores Económicos,Indicadores económicos,Renta,Neta anual,NaN,Renta,Renta neta media anual de los hogares (Urban A...,45064

In [403]:
# Display unique dataset names
indicators_2025["neighbourhood_name"].nunique()

131

In [404]:
# Filter DF to only include 2025 

indicators_2025 = indicators_2025.loc[
    (indicators_2025['dataset_version'] == 2025)]
indicators_2025.head

<bound method NDFrame.head of         row_no  dataset_version              city  district_code  \
96528    96529             2025  Ciudad de Madrid            1.0
96529    96530             2025  Ciudad de Madrid            1.0
96530    96531             2025  Ciudad de Madrid            1.0
96531    96532             2025  Ciudad de Madrid            1.0
96532    96533             2025  Ciudad de Madrid            1.0
...        ...              ...               ...            ...
116789  116790             2025  Ciudad de Madrid           21.0
116790  116791             2025  Ciudad de Madrid           21.0
116791  116792             2025  Ciudad de Madrid           21.0
116792  116793             2025  Ciudad de Madrid           21.0
116793  116794             2025  Ciudad de Madrid           21.0

       district_name  neighbourhood_code neighbourhood_name  year        date  \
96528         Centro                11.0            Palacio  2025  01/01/2025
96529         Centro                11.0            Palacio  2025  01/01/2025
96530         Centro                11.0            Palacio  2025  01/01/2025
96531         Centro                11.0            Palacio  2025  01/01/2025
96532         Centro                11.0            Palacio  2025  01/01/2025
...              ...                 ...                ...   ...         ...
116789       Barajas               214.0              Timón  2025  01/01/2025
116790       Barajas               215.0         Corralejos  2025  01/01/2025
116791       Barajas               215.0         Corralejos  2025  01/01/2025
116792       Barajas               215.0         Corralejos  2025  01/01/2025
116793       Barajas               215.0         Corralejos  2025  01/01/2025

                                              data_source  \
96528                  Estadística Ayuntamiento de Madrid
96529                  Estadística Ayuntamiento de Madrid
96530                  Estadística Ayuntamiento de Madrid
96531                  Estadística Ayuntamiento de Madrid
96532                  Estadística Ayuntamiento de Madrid
...                                                   ...
116789  Portal de datos abiertos del Ayuntamiento de M...
116790  Portal de datos abiertos del Ayuntamiento de M...
116791  Portal de datos abiertos del Ayuntamiento de M...
116792  Portal de datos abiertos del Ayuntamiento de M...
116793  Portal de datos abiertos del Ayuntamiento de M...

                                        main_category  \
96528   Características Generales del Distrito-Barrio
96529   Características Generales del Distrito-Barrio
96530                          Población del distrito
96531                          Población del distrito
96532                          Población del distrito
...                                               ...
116789                             Empresa y comercio
116790                             Empresa y comercio
116791                             Empresa y comercio
116792                             Empresa y comercio
116793                             Empresa y comercio

                         subcategory       indicator_level1 indicator_level2  \
96528                            NaN             Superficie              NaN
96529                            NaN  Densidad de población              NaN
96530        Estructura de población   Número de Habitantes              NaN
96531        Estructura de población   Número de Habitantes          Hombres
96532        Estructura de población   Número de Habitantes          Mujeres
...                              ...                    ...              ...
116789  Locales en uso como vivienda                Locales     Uso vivienda
116790                 Total locales                Locales            Total
116791              Locales abiertos                Locales         Abiertos
116792              Locales cerrados                Locales         Cerrados
116793  Locales en uso como vivienda                Locales     Uso vivienda

       indicator_level3            unit  \
96528               NaN              Ha
96529               NaN  Habitantes/Ha.
96530               NaN      Habitantes
96531               NaN      Habitantes
96532               NaN      Habitantes
...                 ...             ...
116789              NaN          Número
116790              NaN          Número
116791              NaN          Número
116792              NaN          Número
116793              NaN          Número

                                           indicator_name indicator_value
96528                                    Superficie (ha.)          146,99
96529                       Población densidad (hab./ha.)     163,2832165
96530                                   Número habitantes           24001
96531                                   Población hombres           11693
96532                                   Población mujeres           12308
...                                                   ...             ...
116789  Número de locales dados de alta en uso como vi...              17
116790            Número de locales dados de alta totales             442
116791           Número de locales dados de alta abiertos             392
116792           Número de locales dados de alta cerrados              50
116793  Número de locales dados de alta en uso como vi...               1

[14933 rows x 18 columns]>

In [405]:
# Confirm the filter worked
indicators_2025['dataset_version'].nunique()

1

In [406]:
# Count missing values 

indicators_2025.isnull().sum()

#note: not an issue that subcategory and indiciator in some places are null as we are using indicator_name
# rename files later so are appropriate

row_no                   0
dataset_version          0
city                     0
district_code            0
district_name            0
neighbourhood_code       0
neighbourhood_name       0
year                     0
date                     0
data_source              0
main_category            0
subcategory           2358
indicator_level1         0
indicator_level2      1834
indicator_level3      8785
unit                     0
indicator_name           0
indicator_value          0
dtype: int64

In [407]:
# Select relevant columns
indicators_features_2025 = indicators_2025[['district_name','neighbourhood_name','main_category','indicator_name','indicator_value','unit']]

In [408]:
# Display first 5 rows 

indicators_features_2025.head()

,district_name,neighbourhood_name,main_category,indicator_name,indicator_value,unit
96528,Centro,Palacio,Características Generales del Distrito-Barrio,Superficie (ha.),"146,99",Ha
96529,Centro,Palacio,Características Generales del Distrito-Barrio,Población densidad (hab./ha.),"163,2832165",Habitantes/Ha.
96530,Centro,Palacio,Población del distrito,Número habitantes,24001,Habitantes
96531,Centro,Palacio,Población del distrito,Población hombres,11693,Habitantes
96532,Centro,Palacio,Población del distrito,Población mujeres,12308,Habitantes

In [409]:
# Sort by neighbourhood name in descending order

indicators_features_2025 = indicators_features_2025.sort_values(by="neighbourhood_name", ascending=False)

In [410]:
# Display first 5 rows 

indicators_features_2025.head()

,district_name,neighbourhood_name,main_category,indicator_name,indicator_value,unit
112125,Villaverde,Ángeles,Servicios y equipamientos Municipales,Centros municipales de mayores,2,Equipamientos
112098,Villaverde,Ángeles,Educación,Etapas educativas. total niñas,2221,Personas
112131,Villaverde,Ángeles,Servicios y equipamientos Municipales,Centro de día de atención a niños y niñas (de ...,0,Equipamientos
112130,Villaverde,Ángeles,Servicios y equipamientos Municipales,Centros de atención a la infancia (CAI),0,Equipamientos
112129,Villaverde,Ángeles,Servicios y equipamientos Municipales,Centros de apoyo a las familias (CAF),0,Equipamientos

In [411]:
# Create a list of feature names

selected_features = [
    "Población densidad (hab./ha.)",
    "Población mayor/igual de 25 años con bachiller elemental, graduado escolar, ESO, formación profesional 1º grado",
    "Población mayor/igual de 25 años con enseñanza primaria incompleta",
    "Población mayor/igual de 25 años con estudios superiores, licenciatura, arquitectura, ingeniería sup., estudios sup. no universitarios, doctorado, postgraduado",
    "Población mayor/igual de 25 años con formación profesional 2º grado, bachiller superior o BUP",
    "Población mayor/igual de 25 años con nivel de estudios desconocido y/o no consta",
    "Población mayor/igual de 25 años con titulación media, diplomatura, arquitectura o ingeniería técnica",
    "Población mayor/igual de 25 años que no sabe leer ni escribir o sin estudios",
    "Número de locales dados de alta en uso como vivienda",
    "Número de locales dados de alta totales",
    "Renta media disponible por persona",
    "Renta neta media anual de los hogares (Urban Audit)",
    "Tasa absoluta de paro registrado (febrero)",
    "Tasa de crecimiento demográfico (porcentaje)",
    "Tamaño medio del hogar",
    "Edad media de la población",
    "Porcentaje de envejecimiento (población mayor de 65 años/población total)",
    "Índice de vulnerabilidad bienestar social e igualdad",
    "Índice de vulnerabilidad economía y empleo",
    "Índice de vulnerabilidad educación y cultura",
    "Índice de vulnerabilidad medio ambiente urbano y movilidad",
    "Índice de vulnerabilidad salud"
]

In [412]:
# Check if column contains required values 

indicators_features_2025["indicator_name"].isin(selected_features)

112125    False
112098    False
112131    False
112130    False
112129    False
          ...
106487    False
106488    False
106489    False
106490    False
106434    False
Name: indicator_name, Length: 14933, dtype: bool

In [413]:
# Keep data where condition is true 

filtered_features_2025 = indicators_features_2025.loc[
    indicators_features_2025["indicator_name"].isin(selected_features)
]

In [414]:
# View first 5 rows
filtered_features_2025.head()

,district_name,neighbourhood_name,main_category,indicator_name,indicator_value,unit
112106,Villaverde,Ángeles,Índice de vulnerabilidad,Índice de vulnerabilidad economía y empleo,"10,7014485",Índice
112105,Villaverde,Ángeles,Índice de vulnerabilidad,Índice de vulnerabilidad educación y cultura,"10,75621977",Índice
112104,Villaverde,Ángeles,Índice de vulnerabilidad,Índice de vulnerabilidad medio ambiente urbano...,"6,015725852",Índice
112103,Villaverde,Ángeles,Índice de vulnerabilidad,Índice de vulnerabilidad bienestar social e ig...,"7,794412875",Índice
116697,Villaverde,Ángeles,Empresa y comercio,Número de locales dados de alta en uso como vi...,52,Número

In [415]:
# Check dimensions
filtered_features_2025.shape

(2882, 6)

In [416]:
# Check data types
filtered_features_2025.dtypes

district_name         object
neighbourhood_name    object
main_category         object
indicator_name        object
indicator_value       object
unit                  object
dtype: object

In [417]:
# Pivot table so that each row is one neighbourhood
pivoted_features=filtered_features_2025.pivot(index="neighbourhood_name",columns="indicator_name",values="indicator_value")

In [418]:
# View first 5 rows
pivoted_features.head()

indicator_name,Edad media de la población,Número de locales dados de alta en uso como vivienda,Número de locales dados de alta totales,Población densidad (hab./ha.),"Población mayor/igual de 25 años con bachiller elemental, graduado escolar, ESO, formación profesional 1º grado",Población mayor/igual de 25 años con enseñanza primaria incompleta,"Población mayor/igual de 25 años con estudios superiores, licenciatura, arquitectura, ingeniería sup., estudios sup. no universitarios, doctorado, postgraduado","Población mayor/igual de 25 años con formación profesional 2º grado, bachiller superior o BUP",Población mayor/igual de 25 años con nivel de estudios desconocido y/o no consta,"Población mayor/igual de 25 años con titulación media, diplomatura, arquitectura o ingeniería técnica",...,Renta media disponible por persona,Renta neta media anual de los hogares (Urban Audit),Tamaño medio del hogar,Tasa absoluta de paro registrado (febrero),Tasa de crecimiento demográfico (porcentaje),Índice de vulnerabilidad bienestar social e igualdad,Índice de vulnerabilidad economía y empleo,Índice de vulnerabilidad educación y cultura,Índice de vulnerabilidad medio ambiente urbano y movilidad,Índice de vulnerabilidad salud
neighbourhood_name,,,,,,,,,,,,,,,,,,,,,
Abrantes,"42,52699209",54,886,"217,8128595",9674,3363,3558,5361,0,1738,...,12515,"33622,23","2,854972968","4,75","-4,858374384","7,435267188","10,6795205","13,15590765","5,137581236","6,517903051"
Acacias,"47,95211789",28,1353,"340,4695361",4914,1921,13551,5891,0,3525,...,24444,"52933,24","2,269051322","3,36","-1,119320688","6,838956625","4,9848785","6,82011066","6,257348237","6,147338816"
Adelfas,"45,79960578",8,554,"298,7203496",2472,873,6787,2942,0,1847,...,24543,"53793,35","2,332924586","2,83","-1,019626489","6,368323563","5,089996","3,952607996","6,197105237","6,897477647"
Aeropuerto,"42,31375064",11,815,"0,661050602",596,197,176,328,0,81,...,12420,30541,"2,71448468","3,99","-2,440924435","8,051756063","8,5877015","8,20500377","3,575716927","17,30113977"
Alameda de Osuna,"46,59438994",14,491,"98,75941515",2323,634,6276,3502,0,2135,...,24417,60255,"2,601780338","2,43","-0,960566229","7,385541813","4,3198675","3,691304996","5,384811544","6,682053148"

In [419]:
# Check dimensions
pivoted_features.shape

(131, 22)

In [420]:
# Count missing values 

pivoted_features.isnull().sum()

indicator_name
Edad media de la población                                                                                                                                         0
Número de locales dados de alta en uso como vivienda                                                                                                               0
Número de locales dados de alta totales                                                                                                                            0
Población densidad (hab./ha.)                                                                                                                                      0
Población mayor/igual de 25 años con bachiller elemental, graduado escolar, ESO, formación profesional 1º grado                                                    0
Población mayor/igual de 25 años con enseñanza primaria incompleta                                                                                                 0
Población mayor/igual de 25 años con estudios superiores, licenciatura, arquitectura, ingeniería sup., estudios sup. no universitarios, doctorado, postgraduado    0
Población mayor/igual de 25 años con formación profesional 2º grado, bachiller superior o BUP                                                                      0
Población mayor/igual de 25 años con nivel de estudios desconocido y/o no consta                                                                                   0
Población mayor/igual de 25 años con titulación media, diplomatura, arquitectura o ingeniería técnica                                                              0
Población mayor/igual de 25 años que no sabe leer ni escribir o sin estudios                                                                                       0
Porcentaje de envejecimiento (población mayor de 65 años/población total)                                                                                          0
Renta media disponible por persona                                                                                                                                 0
Renta neta media anual de los hogares (Urban Audit)                                                                                                                0
Tamaño medio del hogar                                                                                                                                             0
Tasa absoluta de paro registrado (febrero)                                                                                                                         0
Tasa de crecimiento demográfico (porcentaje)                                                                                                                       0
Índice de vulnerabilidad bienestar social e igualdad                                                                                                               0
Índice de vulnerabilidad economía y empleo                                                                                                                         0
Índice de vulnerabilidad educación y cultura                                                                                                                       0
Índice de vulnerabilidad medio ambiente urbano y movilidad                                                                                                         0
Índice de vulnerabilidad salud                                                                                                                                     0
dtype: int64

In [421]:
# Rename columns 

pivoted_features.rename(columns={

    "Edad media de la población":
        "average_population_age",

    "Número de locales dados de alta en uso como vivienda":
        "registered_residential_properties",

    "Número de locales dados de alta totales":
        "total_registered_properties",

    "Población densidad (hab./ha.)":
        "population_density",

    "Población mayor/igual de 25 años con bachiller elemental, graduado escolar, ESO, formación profesional 1º grado":
        "population_25_plus_lower_secondary_education",

    "Población mayor/igual de 25 años con enseñanza primaria incompleta":
        "population_25_plus_incomplete_primary_education",

    "Población mayor/igual de 25 años con estudios superiores, licenciatura, arquitectura, ingeniería sup., estudios sup. no universitarios, doctorado, postgraduado":
        "population_25_plus_higher_education",

    "Población mayor/igual de 25 años con formación profesional 2º grado, bachiller superior o BUP":
        "population_25_plus_upper_secondary_education",

    "Población mayor/igual de 25 años con nivel de estudios desconocido y/o no consta":
        "population_25_plus_unknown_education_level",

    "Población mayor/igual de 25 años con titulación media, diplomatura, arquitectura o ingeniería técnica":
        "population_25_plus_technical_diploma",

    "Población mayor/igual de 25 años que no sabe leer ni escribir o sin estudios":
        "population_25_plus_no_formal_education",

    "Porcentaje de envejecimiento (población mayor de 65 años/población total)":
        "ageing_rate",

    "Renta media disponible por persona":
        "average_disposable_income_per_person",

    "Renta neta media anual de los hogares (Urban Audit)":
        "average_annual_net_household_income",

    "Tamaño medio del hogar":
        "average_household_size",

    "Tasa absoluta de paro registrado (febrero)":
        "registered_unemployment_rate",

    "Tasa de crecimiento demográfico (porcentaje)":
        "population_growth_rate",

    "Índice de vulnerabilidad bienestar social e igualdad":
        "social_welfare_and_equality_vulnerability_index",

    "Índice de vulnerabilidad economía y empleo":
        "economy_and_employment_vulnerability_index",

    "Índice de vulnerabilidad educación y cultura":
        "education_and_culture_vulnerability_index",

    "Índice de vulnerabilidad medio ambiente urbano y movilidad":
        "urban_environment_and_mobility_vulnerability_index",

    "Índice de vulnerabilidad salud":
        "health_vulnerability_index"

}, inplace=True)

In [422]:
# View first 5 rows
pivoted_features.head()

indicator_name,average_population_age,registered_residential_properties,total_registered_properties,population_density,population_25_plus_lower_secondary_education,population_25_plus_incomplete_primary_education,population_25_plus_higher_education,population_25_plus_upper_secondary_education,population_25_plus_unknown_education_level,population_25_plus_technical_diploma,...,average_disposable_income_per_person,average_annual_net_household_income,average_household_size,registered_unemployment_rate,population_growth_rate,social_welfare_and_equality_vulnerability_index,economy_and_employment_vulnerability_index,education_and_culture_vulnerability_index,urban_environment_and_mobility_vulnerability_index,health_vulnerability_index
neighbourhood_name,,,,,,,,,,,,,,,,,,,,,
Abrantes,"42,52699209",54,886,"217,8128595",9674,3363,3558,5361,0,1738,...,12515,"33622,23","2,854972968","4,75","-4,858374384","7,435267188","10,6795205","13,15590765","5,137581236","6,517903051"
Acacias,"47,95211789",28,1353,"340,4695361",4914,1921,13551,5891,0,3525,...,24444,"52933,24","2,269051322","3,36","-1,119320688","6,838956625","4,9848785","6,82011066","6,257348237","6,147338816"
Adelfas,"45,79960578",8,554,"298,7203496",2472,873,6787,2942,0,1847,...,24543,"53793,35","2,332924586","2,83","-1,019626489","6,368323563","5,089996","3,952607996","6,197105237","6,897477647"
Aeropuerto,"42,31375064",11,815,"0,661050602",596,197,176,328,0,81,...,12420,30541,"2,71448468","3,99","-2,440924435","8,051756063","8,5877015","8,20500377","3,575716927","17,30113977"
Alameda de Osuna,"46,59438994",14,491,"98,75941515",2323,634,6276,3502,0,2135,...,24417,60255,"2,601780338","2,43","-0,960566229","7,385541813","4,3198675","3,691304996","5,384811544","6,682053148"

In [423]:
# Check columns

pivoted_features.columns

Index(['average_population_age', 'registered_residential_properties',
       'total_registered_properties', 'population_density',
       'population_25_plus_lower_secondary_education',
       'population_25_plus_incomplete_primary_education',
       'population_25_plus_higher_education',
       'population_25_plus_upper_secondary_education',
       'population_25_plus_unknown_education_level',
       'population_25_plus_technical_diploma',
       'population_25_plus_no_formal_education', 'ageing_rate',
       'average_disposable_income_per_person',
       'average_annual_net_household_income', 'average_household_size',
       'registered_unemployment_rate', 'population_growth_rate',
       'social_welfare_and_equality_vulnerability_index',
       'economy_and_employment_vulnerability_index',
       'education_and_culture_vulnerability_index',
       'urban_environment_and_mobility_vulnerability_index',
       'health_vulnerability_index'],
      dtype='object', name='indicator_name')

In [424]:
# Sort data alphabetically by neighbourhood name

pivoted_features=pivoted_features.sort_values('neighbourhood_name')

In [425]:
# Format the values: remove the full stops and replace commas with decimal point

pivoted_features = pivoted_features.replace(r"\.", "", regex=True)
pivoted_features = pivoted_features.replace(",", ".", regex=True)

In [426]:
# Change values to float 

pivoted_features=pivoted_features.astype(float)

In [427]:
# View first 5 rows
pivoted_features.head()

indicator_name,average_population_age,registered_residential_properties,total_registered_properties,population_density,population_25_plus_lower_secondary_education,population_25_plus_incomplete_primary_education,population_25_plus_higher_education,population_25_plus_upper_secondary_education,population_25_plus_unknown_education_level,population_25_plus_technical_diploma,...,average_disposable_income_per_person,average_annual_net_household_income,average_household_size,registered_unemployment_rate,population_growth_rate,social_welfare_and_equality_vulnerability_index,economy_and_employment_vulnerability_index,education_and_culture_vulnerability_index,urban_environment_and_mobility_vulnerability_index,health_vulnerability_index
neighbourhood_name,,,,,,,,,,,,,,,,,,,,,
Abrantes,42.526992,54.0,886.0,217.812860,9674.0,3363.0,3558.0,5361.0,0.0,1738.0,...,12515.0,33622.23,2.854973,4.75,-4.858374,7.435267,10.679521,13.155908,5.137581,6.517903
Acacias,47.952118,28.0,1353.0,340.469536,4914.0,1921.0,13551.0,5891.0,0.0,3525.0,...,24444.0,52933.24,2.269051,3.36,-1.119321,6.838957,4.984878,6.820111,6.257348,6.147339
Adelfas,45.799606,8.0,554.0,298.720350,2472.0,873.0,6787.0,2942.0,0.0,1847.0,...,24543.0,53793.35,2.332925,2.83,-1.019626,6.368324,5.089996,3.952608,6.197105,6.897478
Aeropuerto,42.313751,11.0,815.0,0.661051,596.0,197.0,176.0,328.0,0.0,81.0,...,12420.0,30541.00,2.714485,3.99,-2.440924,8.051756,8.587701,8.205004,3.575717,17.301140
Alameda de Osuna,46.594390,14.0,491.0,98.759415,2323.0,634.0,6276.0,3502.0,0.0,2135.0,...,24417.0,60255.00,2.601780,2.43,-0.960566,7.385542,4.319867,3.691305,5.384812,6.682053

In [428]:
# Check columns

pivoted_features.columns

Index(['average_population_age', 'registered_residential_properties',
       'total_registered_properties', 'population_density',
       'population_25_plus_lower_secondary_education',
       'population_25_plus_incomplete_primary_education',
       'population_25_plus_higher_education',
       'population_25_plus_upper_secondary_education',
       'population_25_plus_unknown_education_level',
       'population_25_plus_technical_diploma',
       'population_25_plus_no_formal_education', 'ageing_rate',
       'average_disposable_income_per_person',
       'average_annual_net_household_income', 'average_household_size',
       'registered_unemployment_rate', 'population_growth_rate',
       'social_welfare_and_equality_vulnerability_index',
       'economy_and_employment_vulnerability_index',
       'education_and_culture_vulnerability_index',
       'urban_environment_and_mobility_vulnerability_index',
       'health_vulnerability_index'],
      dtype='object', name='indicator_name')

In [429]:
# Reset index 
pivoted_features = pivoted_features.reset_index()

In [430]:
# Confirm data types as float and check columns 
pivoted_features.dtypes

indicator_name
neighbourhood_name                                     object
average_population_age                                float64
registered_residential_properties                     float64
total_registered_properties                           float64
population_density                                    float64
population_25_plus_lower_secondary_education          float64
population_25_plus_incomplete_primary_education       float64
population_25_plus_higher_education                   float64
population_25_plus_upper_secondary_education          float64
population_25_plus_unknown_education_level            float64
population_25_plus_technical_diploma                  float64
population_25_plus_no_formal_education                float64
ageing_rate                                           float64
average_disposable_income_per_person                  float64
average_annual_net_household_income                   float64
average_household_size                                float64
registered_unemployment_rate                          float64
population_growth_rate                                float64
social_welfare_and_equality_vulnerability_index       float64
economy_and_employment_vulnerability_index            float64
education_and_culture_vulnerability_index             float64
urban_environment_and_mobility_vulnerability_index    float64
health_vulnerability_index                            float64
dtype: object

In [431]:
# Create new features

pivoted_features['percentage_residential_properties']= pivoted_features['registered_residential_properties']/pivoted_features['total_registered_properties']*100

pivoted_features['percentage_of_population_25_plus_either_higher_ed_or_technical']= (pivoted_features['population_25_plus_higher_education']+ pivoted_features['population_25_plus_technical_diploma'])*100/ (pivoted_features['population_25_plus_lower_secondary_education']+ pivoted_features['population_25_plus_incomplete_primary_education']+pivoted_features['population_25_plus_higher_education']+pivoted_features['population_25_plus_upper_secondary_education']+pivoted_features['population_25_plus_unknown_education_level']+pivoted_features['population_25_plus_technical_diploma']+pivoted_features['population_25_plus_no_formal_education'])

In [432]:
# Confirm column names and datatypes
pivoted_features.dtypes

indicator_name
neighbourhood_name                                                 object
average_population_age                                            float64
registered_residential_properties                                 float64
total_registered_properties                                       float64
population_density                                                float64
population_25_plus_lower_secondary_education                      float64
population_25_plus_incomplete_primary_education                   float64
population_25_plus_higher_education                               float64
population_25_plus_upper_secondary_education                      float64
population_25_plus_unknown_education_level                        float64
population_25_plus_technical_diploma                              float64
population_25_plus_no_formal_education                            float64
ageing_rate                                                       float64
average_disposable_income_per_person                              float64
average_annual_net_household_income                               float64
average_household_size                                            float64
registered_unemployment_rate                                      float64
population_growth_rate                                            float64
social_welfare_and_equality_vulnerability_index                   float64
economy_and_employment_vulnerability_index                        float64
education_and_culture_vulnerability_index                         float64
urban_environment_and_mobility_vulnerability_index                float64
health_vulnerability_index                                        float64
percentage_residential_properties                                 float64
percentage_of_population_25_plus_either_higher_ed_or_technical    float64
dtype: object

In [433]:
# Drop columns that are no longer needed
features_2025_prepared= pivoted_features.drop(columns=["population_25_plus_lower_secondary_education",
                                                          "population_25_plus_incomplete_primary_education",
                                                          "population_25_plus_higher_education",
                                                          "population_25_plus_upper_secondary_education",
                                                          "population_25_plus_unknown_education_level",
                                                          "population_25_plus_technical_diploma",
                                                          "population_25_plus_no_formal_education",
                                                          "registered_residential_properties",
                                                          "total_registered_properties"])

In [434]:
# Remove the label for columns left from pivot

features_2025_prepared.columns.name = None

In [435]:
# Confirm column names and datatypes
features_2025_prepared.dtypes

neighbourhood_name                                                 object
average_population_age                                            float64
population_density                                                float64
ageing_rate                                                       float64
average_disposable_income_per_person                              float64
average_annual_net_household_income                               float64
average_household_size                                            float64
registered_unemployment_rate                                      float64
population_growth_rate                                            float64
social_welfare_and_equality_vulnerability_index                   float64
economy_and_employment_vulnerability_index                        float64
education_and_culture_vulnerability_index                         float64
urban_environment_and_mobility_vulnerability_index                float64
health_vulnerability_index                                        float64
percentage_residential_properties                                 float64
percentage_of_population_25_plus_either_higher_ed_or_technical    float64
dtype: object

In [436]:
# view first 10 

features_2025_prepared.head(10)

,neighbourhood_name,average_population_age,population_density,ageing_rate,average_disposable_income_per_person,average_annual_net_household_income,average_household_size,registered_unemployment_rate,population_growth_rate,social_welfare_and_equality_vulnerability_index,economy_and_employment_vulnerability_index,education_and_culture_vulnerability_index,urban_environment_and_mobility_vulnerability_index,health_vulnerability_index,percentage_residential_properties,percentage_of_population_25_plus_either_higher_ed_or_technical
0,Abrantes,42.526992,217.812860,16.763353,12515.0,33622.23,2.854973,4.75,-4.858374,7.435267,10.679521,13.155908,5.137581,6.517903,6.094808,21.360868
1,Acacias,47.952118,340.469536,26.544208,24444.0,52933.24,2.269051,3.36,-1.119321,6.838957,4.984878,6.820111,6.257348,6.147339,2.069475,56.354576
2,Adelfas,45.799606,298.720350,23.095926,24543.0,53793.35,2.332925,2.83,-1.019626,6.368324,5.089996,3.952608,6.197105,6.897478,1.444043,56.869978
3,Aeropuerto,42.313751,0.661051,15.135967,12420.0,30541.00,2.714485,3.99,-2.440924,8.051756,8.587701,8.205004,3.575717,17.301140,1.349693,17.306397
4,Alameda de Osuna,46.594390,98.759415,26.510692,24417.0,60255.00,2.601780,2.43,-0.960566,7.385542,4.319867,3.691305,5.384812,6.682053,2.851324,55.965134
5,Almagro,46.356893,213.775456,24.439776,33425.0,78233.57,2.328984,2.08,-2.912966,8.209531,5.104565,5.823923,8.552990,8.523912,0.127173,67.589718
6,Almenara,43.541469,246.297779,18.210876,16415.0,36303.60,2.422079,4.20,-4.382039,5.784871,9.238084,9.208788,7.011487,6.958182,7.428941,36.376597
7,Almendrales,41.668011,320.407640,14.824257,12826.0,33822.43,2.819918,4.67,-4.674836,8.817065,12.138589,10.825345,7.541764,6.842716,6.474820,23.368059
8,Aluche,48.202333,244.778581,27.912372,15162.0,35834.82,2.484171,4.13,-3.518711,6.619567,8.679993,8.875167,7.129954,6.526087,9.598976,26.829224
9,Amposta,42.340086,282.009725,16.411940,10787.0,27218.54,2.684935,5.91,-6.601325,6.705769,11.712597,11.096168,4.726502,8.347488,8.478803,14.554118

In [437]:
# Check dimensions of cleaned dataset

features_2025_prepared.shape

(131, 16)

In [438]:
# Confirm no mising values of cleaned dataset

features_2025_prepared.isna().sum()

neighbourhood_name                                                0
average_population_age                                            0
population_density                                                0
ageing_rate                                                       0
average_disposable_income_per_person                              0
average_annual_net_household_income                               0
average_household_size                                            0
registered_unemployment_rate                                      0
population_growth_rate                                            0
social_welfare_and_equality_vulnerability_index                   0
economy_and_employment_vulnerability_index                        0
education_and_culture_vulnerability_index                         0
urban_environment_and_mobility_vulnerability_index                0
health_vulnerability_index                                        0
percentage_residential_properties                                 0
percentage_of_population_25_plus_either_higher_ed_or_technical    0
dtype: int64

In [439]:
# View description of cleaned dataset

features_2025_prepared.describe()

,average_population_age,population_density,ageing_rate,average_disposable_income_per_person,average_annual_net_household_income,average_household_size,registered_unemployment_rate,population_growth_rate,social_welfare_and_equality_vulnerability_index,economy_and_employment_vulnerability_index,education_and_culture_vulnerability_index,urban_environment_and_mobility_vulnerability_index,health_vulnerability_index,percentage_residential_properties,percentage_of_population_25_plus_either_higher_ed_or_technical
count,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000,131.000000
mean,44.249689,195.034627,19.968737,20787.618321,49182.010229,2.527370,3.653969,-3.460345,7.633588,7.633587,7.633588,7.633588,7.610797,4.744577,44.582669
std,3.152144,127.667108,5.802684,7282.440257,18089.189512,0.292967,1.250658,2.616333,1.855930,2.762033,2.719632,6.456035,2.455904,4.364783,19.184035
min,32.852876,0.184931,3.146629,8042.000000,25584.100000,1.871816,1.580000,-27.368003,5.104424,3.884921,3.492859,2.341587,5.216657,0.000000,10.571276
25%,42.433539,89.614238,16.223680,14798.000000,34756.600000,2.320241,2.640000,-4.390845,6.083702,5.381118,5.586904,5.233123,6.517903,1.195521,27.111402
50%,44.717975,188.308836,21.019846,19248.000000,43946.520000,2.552708,3.500000,-3.080626,7.193694,6.895384,6.820111,5.982777,6.992050,3.233831,44.640523
75%,46.238188,281.703639,24.069170,26254.000000,60108.810000,2.715078,4.470000,-2.277733,8.599486,9.406335,10.022064,7.167637,7.814786,7.408500,63.185324
max,50.853616,479.203664,36.805491,36918.000000,98186.250000,3.400613,7.150000,-0.282518,14.100651,16.690711,13.712178,61.910901,22.782425,18.443396,75.079872

In [440]:
# View summary of cleaned dataset

features_2025_prepared.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131 entries, 0 to 130
Data columns (total 16 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   neighbourhood_name                                              131 non-null    object
 1   average_population_age                                          131 non-null    float64
 2   population_density                                              131 non-null    float64
 3   ageing_rate                                                     131 non-null    float64
 4   average_disposable_income_per_person                            131 non-null    float64
 5   average_annual_net_household_income                             131 non-null    float64
 6   average_household_size                                          131 non-null    float64
 7   registered_unemployment_rate                                    131 non-null    float64
 8   population_growth_rate                                          131 non-null    float64
 9   social_welfare_and_equality_vulnerability_index                 131 non-null    float64
 10  economy_and_employment_vulnerability_index                      131 non-null    float64
 11  education_and_culture_vulnerability_index                       131 non-null    float64
 12  urban_environment_and_mobility_vulnerability_index              131 non-null    float64
 13  health_vulnerability_index                                      131 non-null    float64
 14  percentage_residential_properties                               131 non-null    float64
 15  percentage_of_population_25_plus_either_higher_ed_or_technical  131 non-null    float64
dtypes: float64(15), object(1)
memory usage: 16.5+ KB

In [441]:
# Save prepared dataset 

features_2025_prepared.to_csv(
    "../data/features_2025_prepared.csv",
    index=False
)