# Predicting Madrid Housing Prices Using Socioeconomic Indicators using Machine Learning

In [1]:
# Import the Pandas library for data manipulation and analysis
import pandas as pd

# Import NumPy for numerical operations
import numpy as np

# Import Matplotlib for creating basic charts and graphs
import matplotlib.pyplot as plt

# Import Seaborn for creating attractive statistical visualisations
import seaborn as sns

In [2]:
# Loading Dataset 1: Panel of Sociodemographic Indicators of Districts and Neighborhoods of Madrid
indicators = pd.read_csv("../data/indicators.csv",sep=";")

In [12]:
# Create a clean working copy of dataset
indicators_2025 = indicators.copy()

In [13]:
# Display the first five rows
indicators_2025.head()

,Orden,Periodo panel,ciudad,cod_distrito,distrito,cod_barrio,barrio,año,fecha_indicador,fuente_indicador,categoría_1,categoría_2,indicador_nivel1,indicador_nivel2,indicador_nivel3,unidad_indicador,indicador_completo,valor_indicador
0,1,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),523
1,2,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),258
2,3,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,134881
3,4,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,67829
4,5,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,67052

In [14]:
# Rename columns

indicators_2025.rename(columns={
    "Orden": "row_no",
    "Periodo panel": "dataset_version",
    "ciudad": "city",
    "cod_distrito": "district_code",
    "distrito": "district_name",
    "cod_barrio": "neighbourhood_code",
    "barrio": "neighbourhood_name",
    "año": "year",
    "fecha_indicador": "date",
    "fuente_indicador": "data_source",
    "categoría_1": "main_category",
    "categoría_2": "subcategory",
    "indicador_nivel1": "indicator_level1",
    "indicador_nivel2": "indicator_level2",
    "indicador_nivel3": "indicator_level3",
    "unidad_indicador": "unit",
    "indicador_completo": "indicator_name",
    "valor_indicador": "indicator_value"
}, inplace=True)

In [15]:
# Display the first ten rows following column rename
indicators_2025.head(10)

,row_no,dataset_version,city,district_code,district_name,neighbourhood_code,neighbourhood_name,year,date,data_source,main_category,subcategory,indicator_level1,indicator_level2,indicator_level3,unit,indicator_name,indicator_value
0,1,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),523
1,2,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),258
2,3,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,134881
3,4,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,67829
4,5,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,67052
5,6,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Edad Media,NaN,NaN,Edad,Edad media de la población,"44,03"
6,7,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,0-14,NaN,Personas,Población de 0 a 14 años,10554
7,8,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,15-29,NaN,Personas,Población de 15 a 29 años,21800
8,9,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,30-44,NaN,Personas,Población de 30 a 44 años,42857
9,10,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,45-64,NaN,Personas,Población de 45 a 64 años,38025

In [16]:
# Check number of shapes and rows 
indicators_2025.shape

(116908, 18)

In [17]:
# Display unique dataset names
indicators_2025["neighbourhood_name"].nunique()

131

In [18]:
# Remove rows where neighbourhood_name is missing
indicators_2025= indicators_2025.dropna(subset=["neighbourhood_name"])

In [19]:
# Check number of shapes and rows 
indicators_2025.shape

(84570, 18)

In [20]:
# Check a sample 
indicators_2025.sample(10)

,row_no,dataset_version,city,district_code,district_name,neighbourhood_code,neighbourhood_name,year,date,data_source,main_category,subcategory,indicator_level1,indicator_level2,indicator_level3,unit,indicator_name,indicator_value
19455,19456,2021,Ciudad de Madrid,1.0,Centro,13.0,Cortes,2020,01/01/2020,Portal web del Ayuntamiento de Madrid (https:/...,Índice de vulnerabilidad,territorial,Resultado del índice,Vulnerabilidad,Educación y Cultura,Índice,Índice de vulnerabilidad educación y cultura,"7,29"
43933,43934,2022,Ciudad de Madrid,8.0,Fuencarral-El Pardo,86.0,Valverde,2022,01/01/2022,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,0-14,NaN,Personas,Población de 0 a 14 años,13542
112198,112199,2025,Ciudad de Madrid,17.0,Villaverde,171.0,Villaverde Alto - Casco Histórico de Villaverde,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Educación,Nivel de estudios de la población,Número de personas,Nivel de estudios desconocido y no consta,NaN,Personas,Población mayor/igual de 25 años con nivel de ...,0
58287,58288,2023,Ciudad de Madrid,2.0,Arganzuela,23.0,Chopera,2022,01/01/2022,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Población mayor de 80 años/ Población mayor de...,NaN,Proporción,Porcentaje de sobre-envejecimiento (población ...,"37,33"
94377,94378,2024,Ciudad de Madrid,13.0,Puente de Vallecas,133.0,Palomeras Bajas,2023,28/05/2023,Estadística Ayuntamiento de Madrid,Resultados Elecciones Locales,NaN,Número de votos,Partido Socialista Obrero Español,Municipio,Votos,"Elecciones municipales, votos al Partido Socia...",4577
33108,33109,2021,Ciudad de Madrid,19.0,Vicálvaro,193.0,Valderrivas,2021,01/02/2021,Estadística Ayuntamiento de Madrid,Indicadores Población desempleo,Indicadores Desempleo,Número de personas paradas,Mujeres,NaN,Tasa,Tasa absoluta de paro registrado mujeres,"8,11"
30089,30090,2021,Ciudad de Madrid,15.0,Ciudad Lineal,151.0,Ventas,2020,01/01/2020,Portal de datos abiertos del Ayuntamiento de M...,Indicadores de Vulnerabilidad,Índice de vulnerabilidad territorial,Número de orden,Posición en ranking distritos/barrios,NaN,Número de orden,Posición en el ranking de distritos y/o barrio...,47
78050,78051,2024,Ciudad de Madrid,2.0,Arganzuela,25.0,Delicias,2023,01/01/2023,Estadística Ayuntamiento de Madrid,Educación,Población en etapas educativas,Número de personas,de 6 a 11 años,Niñas,Personas,Población infantil femenina en etapa educativa...,676
98094,98095,2025,Ciudad de Madrid,2.0,Arganzuela,25.0,Delicias,2024,01/01/2024,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,Nacionalidad española,Personas,Personas con nacionalidad española mujeres,13351
57956,57957,2023,Ciudad de Madrid,1.0,Centro,14.0,Justicia,2022,01/01/2022,Estadística Ayuntamiento de Madrid,Educación,Nivel de estudios de la población,Número de personas,"Titulaciones medias, diplomaturas, arquitectur...",NaN,Personas,Población mayor/igual de 25 años con titulació...,1351

In [10]:
#Display unique dataset names
indicators_2025["neighbourhood_name"].nunique()

131

In [23]:
# Filter DF to only include 2025 

indicators_2025 = indicators_2025.loc[
    (indicators_2025['dataset_version'] == 2025)]
indicators_2025

,row_no,dataset_version,city,district_code,district_name,neighbourhood_code,neighbourhood_name,year,date,data_source,main_category,subcategory,indicator_level1,indicator_level2,indicator_level3,unit,indicator_name,indicator_value
96528,96529,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),"146,99"
96529,96530,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),"163,2832165"
96530,96531,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,24001
96531,96532,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,11693
96532,96533,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,12308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116789,116790,2025,Ciudad de Madrid,21.0,Barajas,214.0,Timón,2025,01/01/2025,Portal de datos abiertos del Ayuntamiento de M...,Empresa y comercio,Locales en uso como vivienda,Locales,Uso vivienda,NaN,Número,Número de locales dados de alta en uso como vi...,17
116790,116791,2025,Ciudad de Madrid,21.0,Barajas,215.0,Corralejos,2025,01/01/2025,Portal de datos abiertos del Ayuntamiento de M...,Empresa y comercio,Total locales,Locales,Total,NaN,Número,Número de locales dados de alta totales,442
116791,116792,2025,Ciudad de Madrid,21.0,Barajas,215.0,Corralejos,2025,01/01/2025,Portal de datos abiertos del Ayuntamiento de M...,Empresa y comercio,Locales abiertos,Locales,Abiertos,NaN,Número,Número de locales dados de alta abiertos,392
116792,116793,2025,Ciudad de Madrid,21.0,Barajas,215.0,Corralejos,2025,01/01/2025,Portal de datos abiertos del Ayuntamiento de M...,Empresa y comercio,Locales cerrados,Locales,Cerrados,NaN,Número,Número de locales dados de alta cerrados,50
116793,116794,2025,Ciudad de Madrid,21.0,Barajas,215.0,Corralejos,2025,01/01/2025,Portal de datos abiertos del Ayuntamiento de M...,Empresa y comercio,Locales en uso como vivienda,Locales,Uso vivienda,NaN,Número,Número de locales dados de alta en uso como vi...,1

In [28]:
# Confirming the filter worked
indicators_2025['dataset_version'].nunique()

1

In [25]:
# Count missing values 

indicators_2025.isnull().sum()

#note: not an issue that subcategory and indiciator in some places are null as we are using indicator_name
# rename files later so are appropriate

row_no                   0
dataset_version          0
city                     0
district_code            0
district_name            0
neighbourhood_code       0
neighbourhood_name       0
year                     0
date                     0
data_source              0
main_category            0
subcategory           2358
indicator_level1         0
indicator_level2      1834
indicator_level3      8785
unit                     0
indicator_name           0
indicator_value          0
dtype: int64

In [29]:
#Selecting relevant columns
indicators_features_2025 = indicators_2025[['district_name','neighbourhood_name','main_category','indicator_name','indicator_value','unit']]

In [30]:
# Display first 5 rows 

indicators_features_2025.head()

,district_name,neighbourhood_name,main_category,indicator_name,indicator_value,unit
96528,Centro,Palacio,Características Generales del Distrito-Barrio,Superficie (ha.),"146,99",Ha
96529,Centro,Palacio,Características Generales del Distrito-Barrio,Población densidad (hab./ha.),"163,2832165",Habitantes/Ha.
96530,Centro,Palacio,Población del distrito,Número habitantes,24001,Habitantes
96531,Centro,Palacio,Población del distrito,Población hombres,11693,Habitantes
96532,Centro,Palacio,Población del distrito,Población mujeres,12308,Habitantes

In [31]:
# Sort by neighbourhood name in descending order

indicators_features_2025 = indicators_features_2025.sort_values(by="neighbourhood_name", ascending=False)

In [32]:
# Display first 5 rows 

indicators_features_2025.head()

,district_name,neighbourhood_name,main_category,indicator_name,indicator_value,unit
112125,Villaverde,Ángeles,Servicios y equipamientos Municipales,Centros municipales de mayores,2,Equipamientos
112098,Villaverde,Ángeles,Educación,Etapas educativas. total niñas,2221,Personas
112131,Villaverde,Ángeles,Servicios y equipamientos Municipales,Centro de día de atención a niños y niñas (de ...,0,Equipamientos
112130,Villaverde,Ángeles,Servicios y equipamientos Municipales,Centros de atención a la infancia (CAI),0,Equipamientos
112129,Villaverde,Ángeles,Servicios y equipamientos Municipales,Centros de apoyo a las familias (CAF),0,Equipamientos

In [33]:
# Create a list of feature names

selected_features = [
    "Población densidad (hab./ha.)",
    "Población mayor/igual de 25 años con estudios superiores, licenciatura, arquitectura, ingeniería sup., estudios sup. no universitarios, doctorado, postgraduado",
    "Población mayor/igual de 25 años con titulación media, diplomatura, arquitectura o ingeniería técnica",
    "Número habitantes",
    "Número de locales dados de alta en uso como vivienda",
    "Número de locales dados de alta totales",
    "Renta media disponible por persona",
    "Renta neta media anual de los hogares (Urban Audit)",
    "Tasa absoluta de paro registrado (febrero)",
    "Tasa de crecimiento demográfico (porcentaje)",
    "Tamaño medio del hogar",
    "Edad media de la población",
    "Porcentaje de envejecimiento (población mayor de 65 años/población total)",
    "Índice de vulnerabilidad bienestar social e igualdad",
    "Índice de vulnerabilidad economía y empleo",
    "Índice de vulnerabilidad educación y cultura",
    "Índice de vulnerabilidad medio ambiente urbano y movilidad",
    "Índice de vulnerabilidad salud"
]

In [34]:
# Check if column contains required values 

indicators_features_2025["indicator_name"].isin(selected_features)

112125    False
112098    False
112131    False
112130    False
112129    False
          ...
106487    False
106488    False
106489    False
106490    False
106434    False
Name: indicator_name, Length: 14933, dtype: bool

In [35]:
# Keep data where condition is true 

filtered_features_2025 = indicators_features_2025.loc[
    indicators_features_2025["indicator_name"].isin(selected_features)
]

In [36]:
# view first 5 rows
filtered_features_2025.head()

,district_name,neighbourhood_name,main_category,indicator_name,indicator_value,unit
112106,Villaverde,Ángeles,Índice de vulnerabilidad,Índice de vulnerabilidad economía y empleo,"10,7014485",Índice
112105,Villaverde,Ángeles,Índice de vulnerabilidad,Índice de vulnerabilidad educación y cultura,"10,75621977",Índice
112104,Villaverde,Ángeles,Índice de vulnerabilidad,Índice de vulnerabilidad medio ambiente urbano...,"6,015725852",Índice
112103,Villaverde,Ángeles,Índice de vulnerabilidad,Índice de vulnerabilidad bienestar social e ig...,"7,794412875",Índice
116697,Villaverde,Ángeles,Empresa y comercio,Número de locales dados de alta en uso como vi...,52,Número

In [38]:
filtered_features_2025.shape

(2358, 6)

In [40]:
filtered_features_2025.dtypes

district_name         object
neighbourhood_name    object
main_category         object
indicator_name        object
indicator_value       object
unit                  object
dtype: object

In [42]:
# Pivot table
pivoted_features=filtered_features_2025.pivot(index="neighbourhood_name",columns="indicator_name",values="indicator_value")

In [43]:
# view first 5 rows
pivoted_features.head()

indicator_name,Edad media de la población,Número de locales dados de alta en uso como vivienda,Número de locales dados de alta totales,Número habitantes,Población densidad (hab./ha.),"Población mayor/igual de 25 años con estudios superiores, licenciatura, arquitectura, ingeniería sup., estudios sup. no universitarios, doctorado, postgraduado","Población mayor/igual de 25 años con titulación media, diplomatura, arquitectura o ingeniería técnica",Porcentaje de envejecimiento (población mayor de 65 años/población total),Renta media disponible por persona,Renta neta media anual de los hogares (Urban Audit),Tamaño medio del hogar,Tasa absoluta de paro registrado (febrero),Tasa de crecimiento demográfico (porcentaje),Índice de vulnerabilidad bienestar social e igualdad,Índice de vulnerabilidad economía y empleo,Índice de vulnerabilidad educación y cultura,Índice de vulnerabilidad medio ambiente urbano y movilidad,Índice de vulnerabilidad salud
neighbourhood_name,,,,,,,,,,,,,,,,,,
Abrantes,"42,52699209",54,886,34079,"217,8128595",3558,1738,"16,76335327",12515,"33622,23","2,854972968","4,75","-4,858374384","7,435267188","10,6795205","13,15590765","5,137581236","6,517903051"
Acacias,"47,95211789",28,1353,36546,"340,4695361",13551,3525,"26,54420836",24444,"52933,24","2,269051322","3,36","-1,119320688","6,838956625","4,9848785","6,82011066","6,257348237","6,147338816"
Adelfas,"45,79960578",8,554,19142,"298,7203496",6787,1847,"23,09592641",24543,"53793,35","2,332924586","2,83","-1,019626489","6,368323563","5,089996","3,952607996","6,197105237","6,897477647"
Aeropuerto,"42,31375064",11,815,1961,"0,661050602",176,81,"15,13596716",12420,30541,"2,71448468","3,99","-2,440924435","8,051756063","8,5877015","8,20500377","3,575716927","17,30113977"
Alameda de Osuna,"46,59438994",14,491,20061,"98,75941515",6276,2135,"26,51069182",24417,60255,"2,601780338","2,43","-0,960566229","7,385541813","4,3198675","3,691304996","5,384811544","6,682053148"

In [45]:
pivoted_features.shape

(131, 18)

In [46]:
# Count missing values 

pivoted_features.isnull().sum()

indicator_name
Edad media de la población                                                                                                                                         0
Número de locales dados de alta en uso como vivienda                                                                                                               0
Número de locales dados de alta totales                                                                                                                            0
Número habitantes                                                                                                                                                  0
Población densidad (hab./ha.)                                                                                                                                      0
Población mayor/igual de 25 años con estudios superiores, licenciatura, arquitectura, ingeniería sup., estudios sup. no universitarios, doctorado, postgraduado    0
Población mayor/igual de 25 años con titulación media, diplomatura, arquitectura o ingeniería técnica                                                              0
Porcentaje de envejecimiento (población mayor de 65 años/población total)                                                                                          0
Renta media disponible por persona                                                                                                                                 0
Renta neta media anual de los hogares (Urban Audit)                                                                                                                0
Tamaño medio del hogar                                                                                                                                             0
Tasa absoluta de paro registrado (febrero)                                                                                                                         0
Tasa de crecimiento demográfico (porcentaje)                                                                                                                       0
Índice de vulnerabilidad bienestar social e igualdad                                                                                                               0
Índice de vulnerabilidad economía y empleo                                                                                                                         0
Índice de vulnerabilidad educación y cultura                                                                                                                       0
Índice de vulnerabilidad medio ambiente urbano y movilidad                                                                                                         0
Índice de vulnerabilidad salud                                                                                                                                     0
dtype: int64

In [47]:
# Rename columns 

pivoted_features.rename(columns={

    "Edad media de la población":
        "average_population_age",

    "Número de locales dados de alta en uso como vivienda":
        "registered_residential_properties",

    "Número de locales dados de alta totales":
        "total_registered_properties",

    "Número habitantes":
        "population",

    "Población densidad (hab./ha.)":
        "population_density",

    "Población mayor/igual de 25 años con estudios superiores, licenciatura, arquitectura, ingeniería sup., estudios sup. no universitarios, doctorado, postgraduado":
        "population_25_plus_higher_education",

    "Población mayor/igual de 25 años con titulación media, diplomatura, arquitectura o ingeniería técnica":
        "population_25_plus_technical_diploma",

    "Porcentaje de envejecimiento (población mayor de 65 años/población total)":
        "ageing_rate",

    "Renta media disponible por persona":
        "average_disposable_income_per_person",

    "Renta neta media anual de los hogares (Urban Audit)":
        "average_annual_net_household_income",

    "Tamaño medio del hogar":
        "average_household_size",

    "Tasa absoluta de paro registrado (febrero)":
        "registered_unemployment_rate",

    "Tasa de crecimiento demográfico (porcentaje)":
        "population_growth_rate",

    "Índice de vulnerabilidad bienestar social e igualdad":
        "social_welfare_and_equality_vulnerability_index",

    "Índice de vulnerabilidad economía y empleo":
        "economy_and_employment_vulnerability_index",

    "Índice de vulnerabilidad educación y cultura":
        "education_and_culture_vulnerability_index",

    "Índice de vulnerabilidad medio ambiente urbano y movilidad":
        "urban_environment_and_mobility_vulnerability_index",

    "Índice de vulnerabilidad salud":
        "health_vulnerability_index"

}, inplace=True)

In [48]:
# view first 5 rows
pivoted_features.head()

indicator_name,average_population_age,registered_residential_properties,total_registered_properties,population,population_density,population_25_plus_higher_education,population_25_plus_technical_diploma,ageing_rate,average_disposable_income_per_person,average_annual_net_household_income,average_household_size,registered_unemployment_rate,population_growth_rate,social_welfare_and_equality_vulnerability_index,economy_and_employment_vulnerability_index,education_and_culture_vulnerability_index,urban_environment_and_mobility_vulnerability_index,health_vulnerability_index
neighbourhood_name,,,,,,,,,,,,,,,,,,
Abrantes,"42,52699209",54,886,34079,"217,8128595",3558,1738,"16,76335327",12515,"33622,23","2,854972968","4,75","-4,858374384","7,435267188","10,6795205","13,15590765","5,137581236","6,517903051"
Acacias,"47,95211789",28,1353,36546,"340,4695361",13551,3525,"26,54420836",24444,"52933,24","2,269051322","3,36","-1,119320688","6,838956625","4,9848785","6,82011066","6,257348237","6,147338816"
Adelfas,"45,79960578",8,554,19142,"298,7203496",6787,1847,"23,09592641",24543,"53793,35","2,332924586","2,83","-1,019626489","6,368323563","5,089996","3,952607996","6,197105237","6,897477647"
Aeropuerto,"42,31375064",11,815,1961,"0,661050602",176,81,"15,13596716",12420,30541,"2,71448468","3,99","-2,440924435","8,051756063","8,5877015","8,20500377","3,575716927","17,30113977"
Alameda de Osuna,"46,59438994",14,491,20061,"98,75941515",6276,2135,"26,51069182",24417,60255,"2,601780338","2,43","-0,960566229","7,385541813","4,3198675","3,691304996","5,384811544","6,682053148"