# Predicting Madrid Housing Prices Using Socioeconomic Indicators using Machine Learning

In [21]:
# Import the Pandas library for data manipulation and analysis
import pandas as pd

# Import NumPy for numerical operations
import numpy as np

# Import Matplotlib for creating basic charts and graphs
import matplotlib.pyplot as plt

# Import Seaborn for creating attractive statistical visualisations
import seaborn as sns

In [22]:
# Loading Dataset 1: Panel of Sociodemographic Indicators of Districts and Neighborhoods of Madrid
indicators = pd.read_csv("../data/indicators.csv",sep=";")

In [23]:
# Create a clean working copy of dataset
indicators_clean = indicators.copy()

In [24]:
# Display the first five rows
indicators_clean.head()

,Orden,Periodo panel,ciudad,cod_distrito,distrito,cod_barrio,barrio,año,fecha_indicador,fuente_indicador,categoría_1,categoría_2,indicador_nivel1,indicador_nivel2,indicador_nivel3,unidad_indicador,indicador_completo,valor_indicador
0,1,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),523
1,2,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),258
2,3,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,134881
3,4,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,67829
4,5,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,67052

In [25]:
# Rename columns

indicators_clean.rename(columns={
    "Orden": "row_no",
    "Periodo panel": "dataset_version",
    "ciudad": "city",
    "cod_distrito": "district_code",
    "distrito": "district_name",
    "cod_barrio": "neighbourhood_code",
    "barrio": "neighbourhood_name",
    "año": "year",
    "fecha_indicador": "date",
    "fuente_indicador": "data_source",
    "categoría_1": "main_category",
    "categoría_2": "subcategory",
    "indicador_nivel1": "indicator_level1",
    "indicador_nivel2": "indicator_level2",
    "indicador_nivel3": "indicator_level3",
    "unidad_indicador": "unit",
    "indicador_completo": "indicator_name",
    "valor_indicador": "indicator_value"
}, inplace=True)

In [26]:
# Display the first ten rows following column rename
indicators_clean.head(10)

,row_no,dataset_version,city,district_code,district_name,neighbourhood_code,neighbourhood_name,year,date,data_source,main_category,subcategory,indicator_level1,indicator_level2,indicator_level3,unit,indicator_name,indicator_value
0,1,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),523
1,2,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),258
2,3,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,134881
3,4,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,67829
4,5,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,67052
5,6,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Edad Media,NaN,NaN,Edad,Edad media de la población,"44,03"
6,7,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,0-14,NaN,Personas,Población de 0 a 14 años,10554
7,8,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,15-29,NaN,Personas,Población de 15 a 29 años,21800
8,9,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,30-44,NaN,Personas,Población de 30 a 44 años,42857
9,10,2020,Ciudad de Madrid,1.0,Centro,NaN,NaN,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,45-64,NaN,Personas,Población de 45 a 64 años,38025

In [27]:
# Checking dataset coverage across different years
indicators_clean["dataset_version"].value_counts().sort_index()

dataset_version
2020    18846
2021    19493
2022    18906
2023    19578
2024    19569
2025    20516
Name: count, dtype: int64

In [28]:
#Display unique dataset names
indicators_clean["neighbourhood_name"].nunique()

131

In [29]:
# Remove rows where neighbourhood_name is missing
indicators_clean_n= indicators_clean.dropna(subset=["neighbourhood_name"])

In [30]:
indicators_clean_n.sample(10)

,row_no,dataset_version,city,district_code,district_name,neighbourhood_code,neighbourhood_name,year,date,data_source,main_category,subcategory,indicator_level1,indicator_level2,indicator_level3,unit,indicator_name,indicator_value
56581,56582,2022,Ciudad de Madrid,2.0,Arganzuela,27.0,Atocha,2022,01/01/2022,Portal de datos abiertos del Ayuntamiento de M...,Empresa y comercio,Locales cerrados,Locales,Cerrados,NaN,Número,Número de locales dados de alta cerrados,47
69928,69929,2023,Ciudad de Madrid,15.0,Ciudad Lineal,156.0,San Juan Bautista,2022,01/01/2022,Portal web del Ayuntamiento de Madrid (https:/...,Índice de vulnerabilidad,territorial,Resultado del índice,Vulnerabilidad,Bienestar social e Igualdad,Índice,Índice de vulnerabilidad bienestar social e ig...,"8,36"
81090,81091,2024,Ciudad de Madrid,6.0,Tetuán,64.0,Almenara,2023,01/01/2023,Estadística Ayuntamiento de Madrid,Educación,Población en etapas educativas,Número de personas,de 0 a 2 años,Niñas,Personas,Población infantil femenina en etapa educativa...,254
36352,36353,2021,Ciudad de Madrid,19.0,Vicálvaro,194.0,El Cañaveral,2019,26/05/2019,Estadística Ayuntamiento de Madrid,Resultados Elecciones Locales,NaN,Número de votos,Ciudadanos,Municipio,Votos,"Elecciones municipales, votos a Ciudadanos-Par...",214
50781,50782,2022,Ciudad de Madrid,16.0,Hortaleza,161.0,Palomas,2021,01/01/2021,Estadística Ayuntamiento de Madrid,Educación,Nivel de estudios de la población,Número de personas,"Bachiller Elemental, Graduado Escolar, ESO, Fo...",NaN,Personas,Población mayor/igual de 25 años con bachiller...,469
29684,29685,2021,Ciudad de Madrid,14.0,Moratalaz,146.0,Vinateros,2021,01/02/2021,Estadística Ayuntamiento de Madrid,Indicadores Población desempleo,Indicadores Desempleo,Número de personas paradas,Hombres,De 25 a 44 años,Tasa,Tasa de desempleo en hombres de 25 a 44 años,"9,07"
76079,76080,2023,Ciudad de Madrid,18.0,Villa de Vallecas,183.0,Ensanche de Vallecas,2021,01/01/2021,Estadística Ayuntamiento de Madrid,Indicadores Económicos,Indicadores económicos,Renta,Neta,Per cápita,Renta,Renta media disponible por persona,15026
57333,57334,2023,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2023,01/01/2023,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,45-64,NaN,Personas,Población de 45 a 64 años,7268
192,193,2020,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2019,01/01/2019,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,0-14,NaN,Personas,Población de 0 a 14 años,1781
62291,62292,2023,Ciudad de Madrid,7.0,Chamberí,72.0,Arapiles,2023,01/01/2023,Estadística Ayuntamiento de Madrid,Indicadores Población desempleo,Población desempleo,Número de personas paradas,Mujeres,NaN,Personas,Paro registrado (número de personas registrada...,413

In [31]:
# Obtaining the neighbourhood names to compare for obtaining a foreign key for the other dataset

indicators_clean_n[
    ["neighbourhood_code", "neighbourhood_name"]
].drop_duplicates().head(20)

      neighbourhood_code    neighbourhood_name
186                 11.0               Palacio
269                 12.0           Embajadores
351                 13.0                Cortes
425                 14.0              Justicia
508                 15.0           Universidad
591                 16.0                   Sol
995                 21.0              Imperial
1070                22.0               Acacias
1148                23.0               Chopera
1227                24.0               Legazpi
1301                25.0              Delicias
1376                26.0  Palos de la Frontera
1456                27.0                Atocha
1868                31.0              Pacífico
1949                32.0               Adelfas
2026                33.0              Estrella
2104                34.0                 Ibiza
2180                35.0         Los Jerónimos
2256                36.0            Niño Jesús
2652                41.0             Recoletos

In [32]:
#Display information for 1 neighbourhood in 2025

palacio = indicators_clean_n.loc[
    (indicators_clean_n['dataset_version'] == 2025) &
    (indicators_clean_n['neighbourhood_name']== 'Palacio')]
palacio

# There are 119 rows

,row_no,dataset_version,city,district_code,district_name,neighbourhood_code,neighbourhood_name,year,date,data_source,main_category,subcategory,indicator_level1,indicator_level2,indicator_level3,unit,indicator_name,indicator_value
96528,96529,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Superficie,NaN,NaN,Ha,Superficie (ha.),"146,99"
96529,96530,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Características Generales del Distrito-Barrio,NaN,Densidad de población,NaN,NaN,Habitantes/Ha.,Población densidad (hab./ha.),"163,2832165"
96530,96531,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,NaN,NaN,Habitantes,Número habitantes,24001
96531,96532,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Hombres,NaN,Habitantes,Población hombres,11693
96532,96533,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Estadística Ayuntamiento de Madrid,Población del distrito,Estructura de población,Número de Habitantes,Mujeres,NaN,Habitantes,Población mujeres,12308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116034,116035,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2023,01/01/2023,Estadística Ayuntamiento de Madrid,Indicadores Económicos,Indicadores económicos,Renta,Neta,Per cápita,Renta,Renta media disponible por persona,23770
116190,116191,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Portal de datos abiertos del Ayuntamiento de M...,Empresa y comercio,Total locales,Locales,Total,NaN,Número,Número de locales dados de alta totales,3062
116191,116192,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Portal de datos abiertos del Ayuntamiento de M...,Empresa y comercio,Locales abiertos,Locales,Abiertos,NaN,Número,Número de locales dados de alta abiertos,2617
116192,116193,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Portal de datos abiertos del Ayuntamiento de M...,Empresa y comercio,Locales cerrados,Locales,Cerrados,NaN,Número,Número de locales dados de alta cerrados,445
116193,116194,2025,Ciudad de Madrid,1.0,Centro,11.0,Palacio,2025,01/01/2025,Portal de datos abiertos del Ayuntamiento de M...,Empresa y comercio,Locales en uso como vivienda,Locales,Uso vivienda,NaN,Número,Número de locales dados de alta en uso como vi...,66

In [33]:
# Display the diffrerent main categories of the indicators

palacio["main_category"].value_counts()

main_category
Población del distrito                           32
Educación                                        22
Servicios y equipamientos Municipales            16
Indicadores Población desempleo                  12
Resultados Elecciones Locales                    10
Vivienda                                          6
Índice de vulnerabilidad                          5
Empresa y comercio                                5
Participación ciudadana                           5
Indicadores Económicos                            4
Características Generales del Distrito-Barrio     2
Name: count, dtype: int64

In [34]:
# Display the diffrerent subcateogries of the indicators

palacio["subcategory"].value_counts()

subcategory
Estructura de población                 24
Población en etapas educativas          15
Población desempleo                     12
Servicios Sociales Municipales           8
Nivel de estudios de la población        7
Estructura de los hogares                6
Entidades de participación ciudadana     5
Territorial                              5
Indicadores económicos                   4
Deportes                                 4
Educación                                2
Cultura                                  2
Dinámica demográfica                     2
Recursos municipales                     1
Total locales                            1
Locales abiertos                         1
Locales cerrados                         1
Locales en uso como vivienda             1
Name: count, dtype: int64

In [35]:
# Understanding if each neighbourhood in 2025 has the same amount of rows or if there are likely whitespaces
# part 1: Create a catalog grouped by neighbourhood name
neighbourhood_catalog = (indicators_clean_n[indicators_clean_n["dataset_version"] == 2025]
    .groupby("neighbourhood_name")
    .size()
    .reset_index(name="row_count")
)
neighbourhood_catalog

    neighbourhood_name  row_count
0             Abrantes        111
1              Acacias        115
2              Adelfas        115
3           Aeropuerto        107
4     Alameda de Osuna        116
..                 ...        ...
126          Vinateros        112
127       Vista Alegre        119
128              Zofío        114
129            Águilas        119
130            Ángeles        115

[131 rows x 2 columns]

In [36]:
# Understanding if each neighbourhood in 2025 has the same amount of rows or if there are like whitespaces 
# part 2: Save to Excel
neighbourhood_catalog.to_excel(
    "../outputs/neighbourhood_catalog.xlsx",
    index=False
)

In [37]:
# Retain only columns with information on types of indicies using palacio 
n_indicator_catalog= palacio[
    [
        "main_category",
        "subcategory",
        "indicator_name",
        "unit"
    ]]

In [38]:
# Remove duplicates
n_indicator_catalog = n_indicator_catalog.drop_duplicates()

In [39]:
# Sort alphabetically
n_indicator_catalog = n_indicator_catalog.sort_values(
    ["main_category", "subcategory", "indicator_name"]
)

In [40]:
# Save to Excel
n_indicator_catalog.to_excel(
    "../outputs/n_indicator_catalog.xlsx",
    index=False
)

# Selecting features for the ML model

After exporting the indicator names for the Palacio neighbourhood, I reviewed the available indicators and selected 15 feature variables for my machine learning model. An English translation of each selected indicator is provided below. Some of the selected features require multiple columns to be combined (e.g. percentages ) before they can be used in the final dataset these are indicated with an asterisk.

No.	Selected Feature Variable
- 1	Population density (inhabitants per hectare)
- 2	Percentage of population aged 25+ with higher education (university degree, postgraduate or doctorate) or diploma/technical degree *
- 3	Percentage of registered housing over total registered premises *
- 4	Average disposable income per person
- 5	Average annual net household income (Urban Audit)
- 6	Registered unemployment rate (February)
- 7	Population growth rate (%)
- 8	Average household size
- 9	Average age
- 10 Ageing index (% aged 65+)
- 11 Social welfare and equality vulnerability index
- 12 Economic and employment vulnerability index
- 13 Education and culture vulnerability index
- 14 Urban environment and mobility vulnerability index
- 15 Health vulnerability index