Predicting Madrid Housing Prices Using Socioeconomic Indicators using Machine Learning

In [624]:
# Import libraries 

# Import the Pandas library for data manipulation and analysis
import pandas as pd

# Import NumPy for numerical operations
import numpy as np

# Import Matplotlib for creating basic charts and graphs
import matplotlib.pyplot as plt

# Import Seaborn for creating attractive statistical visualisations
import seaborn as sns

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

from sklearn.metrics import (mean_absolute_error,mean_squared_error,r2_score)

In [625]:
# Load datasets

features = pd.read_csv("../data/features_2025_prepared.csv")
target = pd.read_csv("../data/prices_2025_prepared.csv")

In [626]:
# Preview dataset- target

features.head()

,neighbourhood_name,average_population_age,population_density,ageing_rate,average_disposable_income_per_person,average_annual_net_household_income,average_household_size,registered_unemployment_rate,population_growth_rate,social_welfare_and_equality_vulnerability_index,economy_and_employment_vulnerability_index,education_and_culture_vulnerability_index,urban_environment_and_mobility_vulnerability_index,health_vulnerability_index,percentage_residential_properties,percentage_of_population_25_plus_either_higher_ed_or_technical
0,Abrantes,42.526992,217.812860,16.763353,12515.0,33622.23,2.854973,4.75,-4.858374,7.435267,10.679521,13.155908,5.137581,6.517903,6.094808,21.360868
1,Acacias,47.952118,340.469536,26.544208,24444.0,52933.24,2.269051,3.36,-1.119321,6.838957,4.984878,6.820111,6.257348,6.147339,2.069475,56.354576
2,Adelfas,45.799606,298.720350,23.095926,24543.0,53793.35,2.332925,2.83,-1.019626,6.368324,5.089996,3.952608,6.197105,6.897478,1.444043,56.869978
3,Alameda de Osuna,46.594390,98.759415,26.510692,24417.0,60255.00,2.601780,2.43,-0.960566,7.385542,4.319867,3.691305,5.384812,6.682053,2.851324,55.965134
4,Almagro,46.356893,213.775456,24.439776,33425.0,78233.57,2.328984,2.08,-2.912966,8.209531,5.104565,5.823923,8.552990,8.523912,0.127173,67.589718

In [627]:
features.shape

(130, 16)

In [628]:
# Preview dataset- feature

target.head()

  neighbourhood_name  mean_average_price_euros_per_m2
0           Abrantes                          2912.90
1            Acacias                          5736.45
2            Adelfas                          5741.86
3   Alameda de Osuna                          5052.01
4            Almagro                         10795.41

In [629]:
target.shape

(130, 2)

In [630]:
# Merge datasets 

madrid_2025=pd.merge(features, target, how='inner', on='neighbourhood_name')

In [631]:
# Preview dataset- feature

madrid_2025.head()

,neighbourhood_name,average_population_age,population_density,ageing_rate,average_disposable_income_per_person,average_annual_net_household_income,average_household_size,registered_unemployment_rate,population_growth_rate,social_welfare_and_equality_vulnerability_index,economy_and_employment_vulnerability_index,education_and_culture_vulnerability_index,urban_environment_and_mobility_vulnerability_index,health_vulnerability_index,percentage_residential_properties,percentage_of_population_25_plus_either_higher_ed_or_technical,mean_average_price_euros_per_m2
0,Abrantes,42.526992,217.812860,16.763353,12515.0,33622.23,2.854973,4.75,-4.858374,7.435267,10.679521,13.155908,5.137581,6.517903,6.094808,21.360868,2912.90
1,Acacias,47.952118,340.469536,26.544208,24444.0,52933.24,2.269051,3.36,-1.119321,6.838957,4.984878,6.820111,6.257348,6.147339,2.069475,56.354576,5736.45
2,Adelfas,45.799606,298.720350,23.095926,24543.0,53793.35,2.332925,2.83,-1.019626,6.368324,5.089996,3.952608,6.197105,6.897478,1.444043,56.869978,5741.86
3,Alameda de Osuna,46.594390,98.759415,26.510692,24417.0,60255.00,2.601780,2.43,-0.960566,7.385542,4.319867,3.691305,5.384812,6.682053,2.851324,55.965134,5052.01
4,Almagro,46.356893,213.775456,24.439776,33425.0,78233.57,2.328984,2.08,-2.912966,8.209531,5.104565,5.823923,8.552990,8.523912,0.127173,67.589718,10795.41

In [632]:
madrid_2025.shape

(129, 17)

In [633]:
checking_madrid_2025=pd.merge(features, target, how='outer', on='neighbourhood_name')

In [634]:
checking_madrid_2025.head()

,neighbourhood_name,average_population_age,population_density,ageing_rate,average_disposable_income_per_person,average_annual_net_household_income,average_household_size,registered_unemployment_rate,population_growth_rate,social_welfare_and_equality_vulnerability_index,economy_and_employment_vulnerability_index,education_and_culture_vulnerability_index,urban_environment_and_mobility_vulnerability_index,health_vulnerability_index,percentage_residential_properties,percentage_of_population_25_plus_either_higher_ed_or_technical,mean_average_price_euros_per_m2
0,Abrantes,42.526992,217.812860,16.763353,12515.0,33622.23,2.854973,4.75,-4.858374,7.435267,10.679521,13.155908,5.137581,6.517903,6.094808,21.360868,2912.90
1,Acacias,47.952118,340.469536,26.544208,24444.0,52933.24,2.269051,3.36,-1.119321,6.838957,4.984878,6.820111,6.257348,6.147339,2.069475,56.354576,5736.45
2,Adelfas,45.799606,298.720350,23.095926,24543.0,53793.35,2.332925,2.83,-1.019626,6.368324,5.089996,3.952608,6.197105,6.897478,1.444043,56.869978,5741.86
3,Alameda de Osuna,46.594390,98.759415,26.510692,24417.0,60255.00,2.601780,2.43,-0.960566,7.385542,4.319867,3.691305,5.384812,6.682053,2.851324,55.965134,5052.01
4,Almagro,46.356893,213.775456,24.439776,33425.0,78233.57,2.328984,2.08,-2.912966,8.209531,5.104565,5.823923,8.552990,8.523912,0.127173,67.589718,10795.41

In [635]:
checking_madrid_2025.shape

(131, 17)

In [636]:
checking_madrid_2025.isnull().sum()

neighbourhood_name                                                0
average_population_age                                            1
population_density                                                1
ageing_rate                                                       1
average_disposable_income_per_person                              1
average_annual_net_household_income                               1
average_household_size                                            1
registered_unemployment_rate                                      1
population_growth_rate                                            1
social_welfare_and_equality_vulnerability_index                   1
economy_and_employment_vulnerability_index                        1
education_and_culture_vulnerability_index                         1
urban_environment_and_mobility_vulnerability_index                1
health_vulnerability_index                                        1
percentage_residential_properties                                 1
percentage_of_population_25_plus_either_higher_ed_or_technical    1
mean_average_price_euros_per_m2                                   1
dtype: int64

In [637]:
#### qty_of_nuls = 1

checking_madrid_2025.iloc[checking_madrid_2025[(checking_madrid_2025.isnull().sum(axis=1) >= qty_of_nuls)].index]

,neighbourhood_name,average_population_age,population_density,ageing_rate,average_disposable_income_per_person,average_annual_net_household_income,average_household_size,registered_unemployment_rate,population_growth_rate,social_welfare_and_equality_vulnerability_index,economy_and_employment_vulnerability_index,education_and_culture_vulnerability_index,urban_environment_and_mobility_vulnerability_index,health_vulnerability_index,percentage_residential_properties,percentage_of_population_25_plus_either_higher_ed_or_technical,mean_average_price_euros_per_m2
124,Villaverde Alto - Casco Histórico de Villaverde,41.947539,56.23325,15.841722,11511.0,30690.88,2.863833,7.03,-4.99373,8.052392,12.410433,11.228827,5.257673,7.127344,4.217754,15.514601,NaN
125,Villaverde Alto. Casco Histórico de Villaverde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2928.26

In [638]:
# Checking results with nulls 
qty_of_nuls= 1

checking_madrid_2025.iloc[checking_madrid_2025[(checking_madrid_2025.isnull().sum(axis=1) >=qty_of_nuls)].index]

,neighbourhood_name,average_population_age,population_density,ageing_rate,average_disposable_income_per_person,average_annual_net_household_income,average_household_size,registered_unemployment_rate,population_growth_rate,social_welfare_and_equality_vulnerability_index,economy_and_employment_vulnerability_index,education_and_culture_vulnerability_index,urban_environment_and_mobility_vulnerability_index,health_vulnerability_index,percentage_residential_properties,percentage_of_population_25_plus_either_higher_ed_or_technical,mean_average_price_euros_per_m2
124,Villaverde Alto - Casco Histórico de Villaverde,41.947539,56.23325,15.841722,11511.0,30690.88,2.863833,7.03,-4.99373,8.052392,12.410433,11.228827,5.257673,7.127344,4.217754,15.514601,NaN
125,Villaverde Alto. Casco Histórico de Villaverde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2928.26